### ISSUE TITLE
RedisCluster ERROR with authentication

### ISSUE THREAD

**Issue by pythoner02** [Grokzen/redis-py-cluster#106]
I use redis3.0.5 cluster mode.
Here are my code:

from rediscluster import RedisCluster
startup_nodes = [{"host": "192.168.1.2", "port": 7000}]
r = RedisCluster(startup_nodes=startup_nodes, password='py02', decode_responses=True)
print r.exists("key")

when i run this code, it throws an exception:
rediscluster.exceptions.RedisClusterException: ERROR sending 'cluster slots' command to redis server: {'host': '192.168.1.2', 'port': 7000}

Last i found it in rediscluster\nodemanager.py get_redis_link() method

why can't use password? I hope you can explain

Thank you very much!

**Comment by Grokzen** [comment]
If you want/need password support you need to wait for PR #104 to be merged and included in the next release.

**Comment by pythoner02** [comment]
Thanks!
May i ask when the next version will be released?

**Comment by Grokzen** [comment]
I have plans to go through all open PR:s and do some investigation with how `redis-py` `1.10.4` works and after that a release will be made. I would estimate a possible one next week or possibly next weekend if i get blocked with something.
