### ISSUE TITLE
Implement all basic clustermgt commands in client

### ISSUE THREAD

**Issue by Grokzen** [Grokzen/redis-py-cluster#108]
Currently there is a ClusterMgt class that implements some nice functions to deal with a cluster. However the basic commands is not implemented in the client class. All cluster mgt methods should be implemented in the base client and the ClusterMgt class can be used to provide a better use and interface to deal with the cluster.

**Comment by ZuSe** [comment]
+1

**Comment by v6** [comment]
// , :+1: This will make the code that uses this less confusing. 

Until resolution, should we use a different library (redis-py) for non-cluster commands that deal with a given Redis instance directly?

**Comment by Grokzen** [comment]
@v6 If you are thinking about the support that has a PR by iandy has open, yes i would suggest using that for now. I am basing my implementation on that work but with fixes for how it will work when running in a proper cluster. Because in a cluster client, you do not connection to a single node and runs the commands, but they are global and needs targeting inside some of the commands. There is need for development when switching between the 2 implementations. The only other solution would be to implement all commands inside the `ClusterMgmt` class that we already have here because it works in a similar fashion. I will continue with the raw commands and see how usefull the `ClusterMgmt`class is in the future and maybe remove it completly or maybe i will make that one the choice. I am not sure yet.
