### ISSUE TITLE
RedisClusterMgt Nodes function throwing an exception when there is more than 2 flags

### ISSUE THREAD

**Issue by piront** [Grokzen/redis-py-cluster#118]
When a node has more than 2 flags, [RedisClusterMgt.Nodes](https://github.com/Grokzen/redis-py-cluster/blob/unstable/rediscluster/cluster_mgt.py#L118) will throw an exception during the split of flags.

In my case, the flags are "slave,fail,noaddr"

**Comment by Grokzen** [comment]
Hi.

Nice find. It should be easy to fix. Instead of allways assuming the role is the second value, it should be better to just check if `master` or `slave` is in the flags block.

**Comment by Grokzen** [comment]
@piront Closing this because of the merged PR you submited before
