### ISSUE TITLE
scan_iter returns duplicates

### ISSUE THREAD

**Issue by sachinpkale** [Grokzen/redis-py-cluster#121]
I am having 1M+ entries in Redis-Cluster and using following command:

`for key in redis_conn.scan_iter(match='XYZ*', count=1000)`

This is returning duplicates.

**Comment by Grokzen** [comment]
@sachinpkale This commit should fix this issue, c2d305a59e237e286df2c26d6e82bd5364f34cfe. It was a bug where the `SCAN` method would send to both masters and slaves in the cluster and report back the same keys all the time. The commit changes so `SCAN` only asks master nodes in the cluster. I also added the test you have above to validate that it works as intended now.
