### ISSUE TITLE
Use redis-cluster pipeline not find  attribute  'nodes_callbacks'

### ISSUE THREAD

**Issue by guoys** [Grokzen/redis-py-cluster#145]
python2.7 the sample code use pipeline occur this error:

  File "redis_test.py", line 141, in __init__
    self.dbif = DBInterface(cf.dbs[host_indx]['host'], cf.dbs[host_indx]['port'], cf.pipe, cf.count)
  File "redis_test.py", line 89, in __init__
    self.pipe = self.rc.pipeline(transaction=False)
  File "/usr/local/lib/python2.7/site-packages/rediscluster/client.py", line 1023, in pipeline
    nodes_callbacks=self.nodes_callbacks,
AttributeError: 'RedisCluster' object has no attribute 'nodes_callbacks'

what should I do?

**Comment by 72squared** [comment]
the bug is specific to RedisCluster. If you use RedisStrictCluster you won't hit the bug. 

See https://github.com/Grokzen/redis-py-cluster/blob/unstable/rediscluster/client.py#L1023

vs 

https://github.com/Grokzen/redis-py-cluster/blob/unstable/rediscluster/client.py#L195-L202

**Comment by guoys** [comment]
Thanks, the question is solved by this way.
