### ISSUE TITLE
Use cluster management commands have some errors

### ISSUE THREAD

**Issue by ywllx** [Grokzen/redis-py-cluster#147]
i run some cluster management command such as "cluster delsots" on the 3 masters 3 slaves cluster, it need a  node_id args, but it will raise a TypeError.
this is my cluster env

```
> 127.0.0.1:7000> CLUSTER nodes
- 09a04bb91ffa311e1cdd5b778883a60c46313304 127.0.0.1:7004 slave 5790b6ee3317d7a006b336d350d2b7d1135ec91a 0 1464167619108 5 connected
- 7397529702f726de196fe8325a805a5efebb6a50 127.0.0.1:7000 myself,master - 0 0 1 connected 0-3999 4002-4999 5002-5460
- 5790b6ee3317d7a006b336d350d2b7d1135ec91a 127.0.0.1:7001 master - 0 1464167618106 2 connected 5461-10922
- fd6d59e7d658363fa304910112515c08f818cb54 127.0.0.1:7005 slave e81ade1d0deadaa30e679fb9122bfebe9e88b928 0 1464167619108 6 connected
- fd72ca4e22bb2e6f704d6a82eb874e5a75c19003 127.0.0.1:7003 slave 7397529702f726de196fe8325a805a5efebb6a50 0 1464167618607 4 connected
- e81ade1d0deadaa30e679fb9122bfebe9e88b928 127.0.0.1:7002 master - 0 1464167619609 3 connected 10923-16383
```

the next is my test code:
```python
from rediscluster import StrictRedisCluster

startup_nodes = [{"host": "127.0.0.1", "port": "7002"}]

rc = StrictRedisCluster(startup_nodes=startup_nodes, decode_responses=True)

rc.set("foo", "bar")

print(rc.get("foo"))
nodes = rc.cluster_nodes()
for node in nodes:
    print node['port']
    if node['port'] == 7000:
        print node['id']
        id = node['id']
        rc.cluster_delslots(id, 3009, 3011)
```
and this is the excute result:
```python
root@ubunu-test:~/work/test/python# python basic.py 
bar
7005
7001
7002
7004
7003
7000
7397529702f726de196fe8325a805a5efebb6a50
Traceback (most recent call last):
  File "basic.py", line 18, in <module>
    rc.cluster_delslots(id, 3009, 3011)
  File "/usr/local/lib/python2.7/dist-packages/rediscluster/client.py", line 391, in cluster_delslots
    return self.execute_command('CLUSTER DELSLOTS', *slots, node_id=node_id)
  File "/usr/local/lib/python2.7/dist-packages/rediscluster/utils.py", line 93, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rediscluster/client.py", line 309, in execute_command
    return self.parse_response(r, command, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/redis/response_callbacks", line 579, in parse_response
    return self.response_callbacks[command_name](response, **options)
TypeError: bool_ok() got an unexpected keyword argument 'node_id'
```

it seems this command will call the response_callbacks function bool_ok to check the response, and it will pass args "node_id = ....", this args is not used for this command, and the bool_ok is also can not handle it, what this is used? it seems most cluster management commands have this problem. and another problem is the return reslut of the cluster nodes command, it sometimes can not return less than 6 nodes info. i think the result is not correct.
```python
nodes = rc.cluster_nodes()
for node in nodes:
    print node['port']
```

**Comment by Grokzen** [comment]
@ywllx One of the problems was fixed in this commit 97e3f66e376eb2d98edd1a97223e248f26fea526 where i fixed the bool_ok problem. It should fix the other cluster methods that have the same problem with bool_ok error.

I will take another pass on all the `CLUSTER ...` commands again to see if more are generally broken or not.

**Comment by Grokzen** [comment]
@ywllx About the delslot commands. I was thinking about changing it to be abit more magic where you do not need to specify the slot_id for the node that has the slot, but you just specify the slot and the method looks up the node_id by looping over `CLUSTER NODES` and get the id by itself.

**Comment by Grokzen** [comment]
@ywllx I rebuilt the cluster_delslots command in this commit c9648106880c32a511a51c670a00fd3dc6466495 
If you find any other bugs with cluster commands, please open a new issue.
