### ISSUE TITLE
Need more people to manage this Project

### ISSUE THREAD

**Issue by NewBirdForCode** [Grokzen/redis-py-cluster#148]
hi man:
      I have a suggest.
      Now many people focus on this project,but many issues can not be reply in time.Maybe one week,Maybe one month,I wish more people can join this project to improve work efficiency.If  u need partner,I wish I can do for u.

**Comment by Grokzen** [comment]
@NewBirdForCode I know that. I do not have as much free time as i used to have so there is not enough time to spend on this project any longer. PR:s are allways welcome to implement/fix issues. I will probably churn out a new major release with more features and refactoring at the end of the summer and a minor very soon to fix some issues.

About managing this project, there is not anyone right now that i trust enough to grant permissions to do have full rights with the code. The closes person is @72squared that i almost trust blindly with his amazing code becuase he has proven that he know his stuff and commited alot of nice features. No one else has provided that much code as he has.
