### ISSUE TITLE
ensure_same_slot() is broken and unnecessary

### ISSUE THREAD

**Issue by leifkb** [Grokzen/redis-py-cluster#149]
ensure_same_slot(), used by pfcount(), only returns True if there is exactly one key. It never returns True for multiple keys, even if they are in the same slot. Also, I don't see why this check is necessary -- why not just allow the client to receive a CROSSSLOT error directly from the server if the keys are in different slots?

**Comment by Grokzen** [comment]
@leifkb Good catch. I removed the code to make `pfcount` much cleaner and with no custom exception logic. Found in this commit 802436a9904869fccc7576e8129ee98be0dafb6b
