### ISSUE TITLE
duplicate pypi naming

### ISSUE THREAD

**Issue by CrackerJackMack** [Grokzen/redis-py-cluster#150]
Looks like two different projects have identical names in the python module name space.

I'm crossing linking the issues so that the two developers could come to an agreement on module naming.  Not that it would happen often, but the two modules can't co-exist in the same python environment.

## The issue

Both modules install to `site-packages/rediscluster` which while not likely, is still a conflict.

salimane/rediscluster-py/issues/11

**Comment by Grokzen** [comment]
@CrackerJackMack Hi. Not to sound like a grumpy old man but this lib will not change the naming of the module to something else to prevent collisions between the libs.
Some reasons why
 - Changing the namespace is a major task and probably should only be done in a complete rewrite of the lib, or if the lib had plans for a version `2.0.0` where this kind of backwards incompatibility could be introduced.
 - This project is more up to date, the last merged PR in the other project was almost 3 years ago.
 - This project is aimed for implement support for the cluster support in 3.0+, the other lib do not have that right now, but they implement almost the same cluster solution as the 3.0+ but in much more in the client side.
 - The 2 libs is not compatible to be run at the same time even if the name would not collide. It is not recommended to run both in the same python interpreter.

Things that i can probably commit to add here to possibly help the situation:
 - Add to the docs about this problem and that the 2 libs do not work together

**Comment by CrackerJackMack** [comment]
:tophat: Your logic sounds reasonable enough to me.  I only wanted to raise the issue with the projects on the ambiguity.  Like you said, maybe just some cross linking via documentation would be sufficient.

**Comment by Grokzen** [comment]
I will close this issue when i write and commit the docs changes to both readme and read-the-docs

**Comment by Grokzen** [comment]
@CrackerJackMack I added docs in this commit https://github.com/Grokzen/redis-py-cluster/commit/67241ecb811c6e32313d05624a60c7ab19ea3469

Closing the issue as resolved as agreed on above.
