### ISSUE TITLE
Scan_iter only get next cursor from 1 nodes

### ISSUE THREAD

**Issue by RedWhiteMiko** [Grokzen/redis-py-cluster#151]
I'm not sure this is a bug or intended behavior,
scan_iter only iterate from cursor in the last Redis nodes (https://github.com/Grokzen/redis-py-cluster/blob/c2d305a59e237e286df2c26d6e82bd5364f34cfe/rediscluster/client.py#L350), 
resulting the iteration isn't 100% complete with all keys on Redis.

Can anyone clarify?

**Comment by Grokzen** [comment]
@RedWhiteMiko Great catch. Let me play with it some and see what i can find out about this.

**Comment by RedWhiteMiko** [comment]
Hi @Grokzen, I changes the scan_iter like this to get cursor from all nodes,
is there a way to run `self.scan(cursor=cursors[node], match=match, count=count)` only in specified node instead of all_masters()?

```
        cursors = {}
        master_count = 0
        for master_node in self.connection_pool.nodes.all_masters():
            cursors[master_node["name"]] = '0'
            master_count += 1

        while (sum(cursors[_] == 0 for _ in cursors)) != master_count:
            for node in cursors:
                if(cursors[node] == 0):
                    continue
                # This should run in specified node instead all nodes
                for _, node_data in self.scan(cursor=cursors[node], match=match, count=count).items():
                    cursor, data = node_data
                    if(_ == node):
                        cursors[_] = cursor

                    for item in data:
                        yield item
```

**Comment by korvus81** [comment]
Here was my attempt to fix it that I *think* works.  This is based on the code @RedWhiteMiko  started, but I dug in to figure out how to get master connections properly (at least, it seems to work...).  This particular piece of code was written outside the library instead of as a replacement for the scanIter code in the redis-py-cluster, so there are a few small differences from that perspective.

```
    # stolen from redis-py client.py
    def _parse_scan(self, response, **options):
        cursor, r = response
        return long(cursor), r

    def _scanIterHelper(self, match=None):
        cursors = {}
        nodeData = {}
        for master_node in self._redis.connection_pool.nodes.all_masters():
            cursors[master_node["name"]] = "0"
            nodeData[master_node["name"]] = master_node

        while not all(cursors[node] == 0 for node in cursors):
            for node in cursors:
                if cursors[node] == 0:
                    continue
                try:
                    conn = self._redis.connection_pool.get_connection_by_node(nodeData[node])
                    if match is not None:
                        conn.send_command("SCAN", cursors[node], match)
                    else:
                        conn.send_command("SCAN", cursors[node])
                    raw_resp = conn.read_response()
                    # if you don't release the connection, the driver will make another, and you will hate your life
                    self._redis.connection_pool.release(conn)
                    cur, resp = self._parse_scan(raw_resp)
                    cursors[node] = cur
                    for r in resp:
                        yield r
                except:
                    logger.exception("Error in _scanIterHelper")
                    return
```

**Comment by Grokzen** [comment]
@korvus81 I tried your code and when i ran the test suite for the `scan_iter` method i got the following output from the tests

```
tests/test_commands.py ['a', 'b', 'c']
F

============================================================== FAILURES =======================================
__________________________________________________ TestRedisCommands.test_scan_iter ___________________________

self = <tests.test_commands.TestRedisCommands object at 0x7f86f1b6d710>, r = StrictRedisCluster<127.0.0.1:7000>

    def test_scan_iter(self, r):
        r.set('a', 1)
        r.set('b', 2)
        r.set('c', 3)
        keys = list(r.scan_iter())
        print(keys)
        assert set(keys) == set([b('a'), b('b'), b('c')])
>       keys = list(r.scan_iter(match='a'))

tests/test_commands.py:648: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
rediscluster/client.py:577: in scan_iter
    raw_resp = conn.read_response()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = ClusterConnection<host=172.17.0.2,port=7002>

    def read_response(self):
        "Read the response from a previously sent command"
        try:
            response = self._parser.read_response()
        except:
            self.disconnect()
            raise
        if isinstance(response, ResponseError):
>           raise response
E           ResponseError: syntax error
```

Any suggestions on why it would fail on my end but not on yours?

**Comment by Grokzen** [comment]
@RedWhiteMiko If the case is that not all keys is returned in all cases then i would need to get a test data sample that would prove that. The current test suite uses 3 keys in different slots and nodes to show that it works in the basic cases. So where/when would it break down?

**Comment by RedWhiteMiko** [comment]
Hi @Grokzen ,
a simple 26 keys like this will broke the test, the code I posted above will get all the keys but it is inefficient :(
```
def test_scan_iter(self, r):
        r.set('a', 1)
        r.set('b', 2)
        r.set('c', 3)
        r.set('d', 4)
        r.set('e', 5)
        r.set('f', 6)
        r.set('g', 7)
        r.set('h', 8)
        r.set('i', 9)
        r.set('j', 10)
        r.set('k', 11)
        r.set('l', 12)
        r.set('m', 13)
        r.set('n', 14)
        r.set('o', 15)
        r.set('p', 16)
        r.set('q', 17)
        r.set('r', 18)
        r.set('s', 19)
        r.set('t', 20)
        r.set('u', 21)
        r.set('v', 22)
        r.set('w', 23)
        r.set('x', 24)
        r.set('y', 25)
        r.set('z', 26)
        keys = list(r.scan_iter())
>      assert set(keys) == set([b('a'), b('b'), b('c'), b('d'), b('e'), b('f'), b('g'), b('h'), b('i'), b('j'), b('k'), b('l'), b('m'), b('n'), b('o'), b('p'), b('q'), b('r'), b('s'), b('t'), b('u'), b('v'), b('w'), b('x'), b('y'), b('z')])
E       assert set(['b', 'c'...f', 'g', ...]) == set(['a', 'b',...e', 'f', ...])
E         Extra items in the right set:
E         'a'
E         't'

```

**Comment by RedWhiteMiko** [comment]
@Grokzen Also, it break down due the same next iteration value, something like this in the node (with some imaginery iterator value)
* Bold is the cursor value in code

| Iter Value | Redis Node A | Redis Node B  | Redis Node C |
| :-------------: |:-------------:| -----:| :-------------: |:-------------:| -----:|
| Start 0     | Get Next Iter 1 | Get Next Iter 2 | **Get Next Iter 3** |
| Start 3     | Get Next Iter 4 | Get Next Iter 5 | **Get Next Iter 6** |
| Start 6     | Get Next Iter 7 | Get Next Iter 9 | **Get Next Iter 9** |

Whereas the correct iteration should be

| Iter Value A | Iter Value B | Iter Value C | Redis Node A | Redis Node B  | Redis Node C |
| :-------------: |:-------------:| -----:| :-------------: |:-------------:| -----:|
| Start 0      | Start 0 | Start 0 | Get Next 1 | Get Next 2 | Get Next 3 |
| Start 1     | Start 2 | Start 3 | Get Next 4 | Get Next 5 | Get Next 6 |
| Start 4     | Start 5 | Start 6 | Get Next 7 | Get Next 9 | Get Next 9 |

Hopefully it helps, thank you :)

**Comment by Grokzen** [comment]
@RedWhiteMiko @korvus81 I took the code that you provided @korvus81 and tweaked it some to make it work inside the client, fixed a issue with match and added support for count. You can see it in this branch/commit here https://github.com/Grokzen/redis-py-cluster/commit/965d34d03bce021449cc7e2a526374932a18a66e Play with it some if you have time to verify that it works better. I extended the tests to now use ~40-50 keys during the test and it all works again.

My current plan for this fix is to keep it in the branch and battle test it some more and not include it in 1.3.0 (that will be done later tonight) but when it feels good enough i will make a 1.3.1 with the fix in it. Also probably will mention that this method is broken in 1.3.0 but has a pending fix for 1.3.1.

**Comment by korvus81** [comment]
Looks good to me!  Sorry, I actually found the match bug after it got merged into a release because I only tested locally without a match parameter (in my infinite wisdom).  Thanks for coming up with a resolution!

**Comment by Grokzen** [comment]
@korvus81 Sounds good to me. I will merge into unstable later and let it bake in there for the next release then.

**Comment by thethomp** [comment]
If you can post once you merge into unstable, I'd be happy to help test as well.

**Comment by Grokzen** [comment]
@korvus81 @thethomp @RedWhiteMiko The branch is not inside unstable and will bake in there for a while before released in 1.3.1. Please test away and if you find issues you can post them in here. I will keep this issue online for a week or so or until i hear from you that it looks ok.

**Comment by thethomp** [comment]
I was able to verify with a couple different test cases that the scan_iter function is now returning 100% of the expected keys. Before I would consistently get back ~.05% less keys then when I used the keys() function. Now they match every time. 

+1 from me to incorporate this fix in the next release!

**Comment by Grokzen** [comment]
@thethomp Just our of curiosity, how big datasets did you run against? I am thinking about increaseing the ammount of random data generated for the tests.

**Comment by thethomp** [comment]
I ran around 10 tests on 2 different data sets. One was around 2 million keys, the other had a little over 8 million keys. I first ran the scans using the current stable code and verified it returned different results than keys(). Then using the unstable branch, ran the same scans, and verified it returned the right numbers. I scanned against both the entire dataset (*) and also subsets of keys using wildcard patterns. All cases returned accurate, verifiable results.

**Comment by thethomp** [comment]
Any ETA on when this may get incorporated into the stable branch and released to the world? Has anyone else found any issues with it?

**Comment by Grokzen** [comment]
@thethomp My current estimate is to get a minor release out by the end of this weekend. I want to get in the pipeline fixes that there is an open MR for still before freezing a release.

**Comment by thethomp** [comment]
:+1: Great, thanks @Grokzen !

**Comment by RedWhiteMiko** [comment]
Hi @Grokzen, Thank you for the great works!
Did some test in my cluster with 3M data, the results seems to be good for all keys and with some* ! :)
One thing, when I run the test with bigger dataset, in https://github.com/Grokzen/redis-py-cluster/blob/unstable/tests/test_commands.py#L656
shouldn't it be `assert len(set(keys)) == 3`?

**Comment by Grokzen** [comment]
@RedWhiteMiko Yes from what i can understand from the code that is correct. Becuase X is not part of the `alphabet` variable above (do not really know why it is not O.o) then there is only keys in the cluster at that time that is a single letter or `Xa` `Xb` `Xc` and then the `scan_iter` function with argument `X*` will return all three keys that starts with `X...`

**Comment by Grokzen** [comment]
@RedWhiteMiko @korvus81 @thethomp Release `1.3.1` is finally out where this fix is included. If you find any new issues with the new implementation please open up a new ticket. Closing this as fixed. https://github.com/Grokzen/redis-py-cluster/releases/tag/1.3.1
