### ISSUE TITLE
Is redis-cluster-py thread safe?

### ISSUE THREAD

**Issue by dominicfollett** [Grokzen/redis-py-cluster#158]
Can it be used with Flask?

**Comment by Grokzen** [comment]
@dominicfollett Yes it should be that. It tries to use the same mechanisms that redis-py but there is no guaranteees or extensive tests that it works or not. If you find any issues with threads that is reproducable i can look at it. I have not yet seen any indications that it should not be compatible.

**Comment by Grokzen** [comment]
@dominicfollett I would like to add one thing just. I leave no guarantees (the license mentions same thing) that the code works perfect and is thread-safe all the time. It just piggy back on the implementation in `redis-py` and it might be good, it might be bad so you need to test it out yourself and verify that it works as you want inside your specific environment.
