### ISSUE TITLE
Cannot get client via StrictRedisCluster.from_url

### ISSUE THREAD

**Issue by dominicfollett** [Grokzen/redis-py-cluster#159]
```py
RedisCluster.from_url('http://localhost:30001')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../pypy/site-packages/rediscluster/client.py", line 174, in __repr__
    servers = list({'{0}:{1}'.format(nativestr(info['host']), info['port']) for info in self.connection_pool.nodes.startup_nodes})
AttributeError: 'ConnectionPool' object has no attribute 'nodes'
```

I am trying to integrate redis-py-cluster as a flask extension. However, I cannot get the client object this way.

**Comment by dominicfollett** [comment]
When working with Flask, if the object cannot be instantiated at app creation time, it is impossible to instantiate it at a later time when a cluster is reachable. If you try and set the RedisCluster Client Object, it will not persist, and upon every single request the object will be created and removed.

Ideally, it would be useful, if there are no reachable nodes, then client object is still instantiated, and reconnects at a later time if the cluster is reachable.

Forcing the cluster to be reachable upon client instantiation makes it impossible to work with Flask and redis-py-cluster in a reliable manner.

**Comment by Grokzen** [comment]
@dominicfollett I would say that you should really look at the standard solution for using the regular `redis-py` client inside flask becuase that should already be a solved problem. 

I googled quickly and found this extension to flask https://github.com/underyx/flask-redis that provides a redis client in the flask server. If you use that extension and just change the redis client from using the default client to use this cluster client and it should work our of the box.

I will close this issue becuase it has no relation to this client and is something that should be fixed within a flask extension scope and not in here.

**Comment by dominicfollett** [comment]
Hi Grokzen.

Thanks for the reply. My post above is showing that redis-py-cluster does not work out the box with flask-redis because of the from_url method throwing the error above. redis-py allows you to instantiate a client without an endpoint available, redis-py-cluster requires at least one node to be reachable; for clarity see the init method [here](https://github.com/underyx/flask-redis/blob/master/flask_redis/__init__.py).

**Comment by Grokzen** [comment]
@dominicfollett Thanks for the clarifications. The only way that exists to stop the client from querying the cluster at creation time would be to create the client this way `StrictRedisCluster(startup_nodes=..., init_slot_cache=False)` and that will stop the client from querying the cluster at creation time. I do not however remember if that will make it so when the client querys the cluster the first time it will do the cluster discovery part and fail at that time, please try this out and see what happens.

Becuase this client do not override the method `from_url` from redis-py you should be able to use something like this to make it work `RedisCluster.from_url('http://localhost:30001', init_slot_cache=False)`. If this do not work then it might be a case for reimplementing it and fixing any problems that exists or find a different solution that do not requires `from_url`.

Based on the following https://github.com/andymccurdy/redis-py/blob/ac9370f05a86e59f46ad8bf492ece891b4cbb097/redis/client.py#L454

**Comment by dominicfollett** [comment]
Hi Grokzen

I've tried ```StrictRedisCluster(startup_nodes=..., init_slot_cache=False)``` which returns a client object, but does not initiate client discovery  when calling get or set. 

I get around this by catching the related exception, and then calling redis_client.connection_pool.nodes.initialize(), and I keep doing this until a node becomes available.

**Comment by Grokzen** [comment]
@dominicfollett pushing fixing this to next release as i am currently doing a new update release.

**Comment by Grokzen** [comment]
@dominicfollett It was abit easier to implement then i thought. Please have a look at this commit a0b45359fa34fc495813650f971371a9c1acb72b and try it out yourself in the unstable branch. I am currently able to run this piece of code without any issues on my test cluster that i have inside docker

```
url_client = StrictRedisCluster.from_url('http://127.0.0.1:7000')
```

Note that same rules that `startup_nodes` has applies to this case also.

Closing this issue as fixed for now and will be part of next release `1.3.2`

**Comment by dominicfollett** [comment]
@Grokzen great! :)

Thanks for the update, I will give it go soon.
