### ISSUE TITLE
ERR unknown command 'CONFIG' when using Secured Redis

### ISSUE THREAD

**Issue by HuangSuoyuan** [Grokzen/redis-py-cluster#166]
Redis security recommends disabling the CONFIG command so that remote users cannot reconfigure an instance. StrictRedisCluster require access to this in its initialization. Hosted Redis services, like AWS ElastiCache disable this command by default, with no option to re-enable it.

**Comment by Grokzen** [comment]
@HuangSuoyuan Where exactly is this `CONFIG` command running that is required?? Can you please link to what line in what file you are refering to?

**Comment by timonwong** [comment]
A PR had already proposed here: #165 

The `CONFIG GET` command is issued here:
https://github.com/cnu/redis-py-cluster/blob/6c517ad03c62f2a44a90b3e5bb5e764766b568f5/rediscluster/nodemanager.py#L260

**Comment by Grokzen** [comment]
@huangsuoyuan @timonwong i would acctually be more incline to merge this PR #164 instead becuase it solves the problem in a smoother way. Just silently ignore the error becuase of any ResponseError is not good enough. Yes you would have to opt-out from the check but that is a better solution then to change the default behaviour from the current allways on to instead be always silently accept changes and errors in the config.

**Comment by Grokzen** [comment]
Merged #164 so closing this as fixed becuase of that merge.
