### ISSUE TITLE
Is python data type support in schedule?

### ISSUE THREAD

**Issue by hisi-SmallFish** [Grokzen/redis-py-cluster#167]
eg. Dict, List, Set，

In redis these types are supportted

**Comment by Grokzen** [comment]
@hisi-SmallFish i do not get what you mean by that things is supported in `schedule`, can you elaborate on that part?

**Comment by Grokzen** [comment]
@hisi-SmallFish To my knowledge all operations that works in redis-py is implemented in this library and works in both regular client and pipelines.

**Comment by hisi-SmallFish** [comment]
3x for your reply. 

For example, I do the set operation like this:
`rc.set("temp_key", {"key_1": "value_1"})`

then I do get operation, I'll get a unicode result, not the origin value as dict type.
`>>> rc.set("temp_key", {"key_1": "value_1"})`
`True`
`>>> rc.get("temp_key")`
`u"{'key_1': 'value_1'}"`

It means that if I want store data in a non-string type, I will always do the serialization before set and deserialization after get.

**Comment by Grokzen** [comment]
@hisi-SmallFish This is working as intended. The command `SET <key>` is working as intended beucase if you read up on the docs of each command you will se how they work and is supposed to work. Quote from http://redis.io/commands/set `Set key to hold the string value. If key already holds a value, it is overwritten, regardless of its type.` This mean that the set commands only stores strings and not real objects. The underlying library of `redis-py` implements this by converting whatever object you pass into it to a string and pushed that string to your redis server. This is why when you get back the data from redis you see it as a string.

Please read up and educate yourself on what functions to use in what usecase before asking what is broken or not.

To see all functions for lists see http://redis.io/commands#list

For all functions for hashes/dicts please see http://redis.io/commands#hash

For any further questions you should ask them in the gitter channel and not through the issue system.
