### ISSUE TITLE
Using pipeline cause Exception: 'tuple' object has no attribute 'position'

### ISSUE THREAD

**Issue by FlyingPengu** [Grokzen/redis-py-cluster#188]
Hello,
I'm trying the pipelining and using following code:
```
rc = StrictRedisCluster(startup_nodes=startup_nodes, decode_responses=True, max_connections=36)
p1 = rc.pipeline()
p1.command_stack.append((["DEL", "abc:" + str(id)], {}))
p1.command_stack.append((["SREM", "abc", str(id)], {}))
p1.execute()
```
and always getting an exception:
`Exception: 'tuple' object has no attribute 'position'`
What I'm doing wrong? It is nearly like the example from the doc. All none-piplining executions are running fine.

Thanks
Thomas

**Comment by FlyingPengu** [comment]
Duplicate! Sorry!

**Comment by Grokzen** [comment]
@FlyingPengu Duplicate of what?

**Comment by Grokzen** [comment]
I see that the code example you are basing this error on is not that updated and in some ways wrong. In general pipelines works the exact same way they do in regular redis-py.
