### ISSUE TITLE
Connection reset error with large data during set operation

### ISSUE THREAD

**Issue by chandu-atina** [Grokzen/redis-py-cluster#191]
We are trying to SET pickled object of size 2.3GB into redis through redis-py-cluster package. Encountered the following error.

> redis.exceptions.ConnectionError: Error 104 while writing to socket. Connection reset by peer.

I would like to understand the root cause. Is it due to input/output buffer limitation at server side or client side ? Is single value (bytes) of 2.3 Gb allowed to store into Redis.

> from rediscluster import StrictRedisCluster
>startup_nodes = [{"host": "10.X.X.100", "port": "7000"},{"host": "10.X.X.101", "port": "7000"},{"host": "10.X.X.102", "port": "7000"}]
>rc = StrictRedisCluster(startup_nodes=startup_nodes, decode_responses=True)
>pickled_object = pickle.dumps(obj_to_be_pickled)
>rc.set('some_key', pickled_object)

Redis Version : 3.2.8 / 64 bit

**Comment by Grokzen** [comment]
@chandu-atina Exceptions caused by the sublibrary redis-py must be reported to them and not here. Unless you can prove that the exception was caused by this library this is not the correct place to report this error.

**Comment by chandu-atina** [comment]
@Grokzen Thanks for the pointer. I'm not aware that redis-py-cluster internally uses redis-py. I tried the same with redis-py and got the same issue. Reported the same in redis-py.
