### ISSUE TITLE
Is there any workaround on pattern subscribe

### ISSUE THREAD

**Issue by hitigon** [Grokzen/redis-py-cluster#193]
I am trying to get key notification on expired keys work with Redis Cluster. As written in `Known limitations with pubsub`, pattern subscribe does not work properly. My understanding is because of endless of channel names but only one slot is determined, causing key notification with listening certain patterns won't work at all.

So, the question is, except moving to non-clustered redis instance, there is any other way I can make it work?

Thanks.

**Comment by Grokzen** [comment]
@hitigon All pubsub related problems with the current impl is all based inside redis itself and how the feature works in a clustered env.  I do not recommend pubsub to be used at all in a clustered env becuase of several reasons that is specefied inside the docs. You trade some reliability for some redundancy but it is not worth it in this case.
