### ISSUE TITLE
How to Scan all keys in Cluster

### ISSUE THREAD

**Issue by malaysarkar** [Grokzen/redis-py-cluster#194]
Hi,
I have seen the document; it says:

> The following commands will only be send to the master nodes in the cluster. Results is returned as a dict with k,v pair (NodeID, Command-Result).
> 
> flushall
> flushdb
> scan

and scan is defined as scan(cursor=0, match=None, count=None)
To scan all keys; we are supposed to call "scan" repeatedly using the cursor we get as reply in every call.
Now if I call scan for first time; I get following output.
```

>>> rc.scan(cursor=0)
{'127.0.0.1:7002': (12288, ['K_949', 'K_12965', 'K_71693', 'K_92200', 'K_73652', 'K_64243', 'K_85587', 'K_72566', 'K_86977', 'K_13461', 'K_21914']), '127.0.0.1:7001': (18432, ['K_3194', 'K_43557', 'K_64999', 'K_91903', 'K_97781', 'K_78847', 'K_44464', 'K_81128', 'K_8901', 'K_85740']), '127.0.0.1:7003': (6144, ['K_80345', 'K_45805', 'K_16637', 'K_53736', 'K_2975', 'K_97021', 'K_54359', 'K_19975', 'K_49648', 'K_75883'])}

```
Thus as mentioned in docs; scan is send to the master nodes in the cluster. Results is returned as a dict with k,v pair (NodeID, Command-Result).

But how to call scan for second time?
Cursor returned by all server are different. Also I can't direct scan to only one server :(

Please suggest a solution.

Thanks,
Malay

**Comment by thethomp** [comment]
You should use scan_iter, I do something along these lines:
`for k in rc.scan_iter(match="pattern*", count=1000):`

**Comment by Grokzen** [comment]
The answer that @thethomp provided is the correct path you should investigate. I consider this question answered and i will close this one. If you have more problems then please open up a new ticket.
