### ISSUE TITLE
Can not connect redis cluster with password

### ISSUE THREAD

**Issue by movingheart** [Grokzen/redis-py-cluster#198]
Environment:
python: 2.7.5
redis: 3.2.8
rediscluster: 1.3.4

error message:
```
`>>> redis_nodes =  [
...     {'host':'spider_slave05','port':'7001','password': 'donews1234'},
...     {'host':'spider_slave06','port':'7001','password': 'donews1234'},
...     {'host':'spider_slave07','port':'7001','password': 'donews1234'},
... ]
>>> from rediscluster import StrictRedisCluster
>>> redisconn = StrictRedisCluster(startup_nodes=redis_nodes, decode_responses=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/rediscluster/client.py", line 181, in __init__
    **kwargs
  File "/usr/lib/python2.7/site-packages/rediscluster/connection.py", line 141, in __init__
    self.nodes.initialize()
  File "/usr/lib/python2.7/site-packages/rediscluster/nodemanager.py", line 183, in initialize
    raise RedisClusterException("ERROR sending 'cluster slots' command to redis server: {0}".format(node))
rediscluster.exceptions.RedisClusterException: ERROR sending 'cluster slots' command to redis server: {'host': 'spider_slave05', 'password': 'donews1234', 'port': '7001'}`
```

**Comment by lacunoc** [comment]
Please make sure to use python3 to connect.

Furthermore ensure that you use at least version 2.10.5-2 of python3-redis (I'm using 2.10.5-2~bpo8+1 from debian jessie-backports).

**Comment by movingheart** [comment]
Have any other solution?
I user python build-in centos. 
Details:
`$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.2.1511 (Core) 
Release:	7.2.1511
Codename:	Core`

**Comment by lacunoc** [comment]
you should be able to install python3.(4/5/6) via your package manager, if it's not installed yet.

use yum f.e.

**Comment by movingheart** [comment]
I have figure out the question by scanning source code.
Correct way of connection as follows:
`>>> redis_nodes =  [
...     {'host':'spider_slave05','port':'7001','password': 'donews1234'},
...     {'host':'spider_slave06','port':'7001','password': 'donews1234'},
...     {'host':'spider_slave07','port':'7001','password': 'donews1234'},
... ]
>>> from rediscluster import StrictRedisCluster
>>> redisconn = StrictRedisCluster(startup_nodes=redis_nodes, decode_responses=True, ,password='donews1234')`
