### ISSUE TITLE
how to add auth in params.

### ISSUE THREAD

**Issue by lukeheng** [Grokzen/redis-py-cluster#200]
like this 
startup_nodes = [{"host": "127.0.0.1", "port": "7000","auth","requirepass"}]

**Comment by Grokzen** [comment]
Like this? https://github.com/Grokzen/redis-py-cluster/blob/unstable/examples/basic_password_protected.py

**Comment by Grokzen** [comment]
Question was answered. Closing this issue. If you have any more practical problems then please open a new issue.

**Comment by elimirks** [comment]
Here is an updated link  https://github.com/Grokzen/redis-py-cluster/blob/master/examples/basic_password_protected.py
