### ISSUE TITLE
redis-py-cluster support part  pipeline ? 

### ISSUE THREAD

**Issue by rfyiamcool** [Grokzen/redis-py-cluster#205]
see title, thank U.

**Comment by AngusP** [comment]
see also #140

**Comment by Grokzen** [comment]
@rfyiamcool I do not really get what you are after. I do not know the concept of "part pipeline". You need to explain what you want further before i can give you a good answer yes or no.

**Comment by Grokzen** [comment]
@rfyiamcool Yes please see #140 as it might be what you are looking for. But becuase you have not updated your question in a while i will now close this issue and if you have some other question with more details then we can handle that in a new issue becuase this one is now stale imo.
