### ISSUE TITLE
Question: Does this library support locking api's in redis-py library?

### ISSUE THREAD

**Issue by noorul** [Grokzen/redis-py-cluster#213]
I think the api in redis-py library for lock uses multiple commands. Will this be safe on redis cluster?

**Comment by Grokzen** [comment]
@noorul If you are refering to the feature with `MULTI/EXEC` that enables batches of commands to be executed then the answer is, `it depends on the use case`.

If you are using normal commands then MULTI/EXEC should be supported and safe to use. If you are using pipelines then it is not really supported that good becuase pipelines is hard to work with in a cluster version of redis.

@noorul Please explain more in detail what you are refering to and possible post a usecase that you want to have and i can answer if it is supporte dor not.

**Comment by AngusP** [comment]
@noorul if you're asking about the `lock` function that returns a `<redis.lock.LuaLock at 0x...>` then that depends on Lua scripting, SETNX, PEXPIRE, GET, PTTL and DEL working in the cluster... All of those are fine in a cluster environment to the best of my knowledge, so the functionality should be the same as on a single Redis instance

**Comment by Grokzen** [comment]
@noorul I would refer to the response from @AngusP on this.

Closing this issue.
