### ISSUE TITLE
All Tests failing on TestScripting.test_script_object

### ISSUE THREAD

**Issue by AngusP** [Grokzen/redis-py-cluster#219]
https://github.com/Grokzen/redis-py-cluster/blob/078867b51b2613ad822c1bcf6997fc29df0ade18/tests/test_scripting.py#L97

`assert not multiply.sha` seems to cause a fail for basically all the unit tests at the moment...

The `sha` member used to be just `''` which will pass `assert not ''`:

https://github.com/andymccurdy/redis-py/blob/d6c300b39ab4c81cd97b81fcd8d25a9cde9476e7/redis/client.py#L2935

But since https://github.com/andymccurdy/redis-py/commit/f49f7d27592a5ed1e7f27f032c1e54d646154c89 is pre-computed as of ~4mo ago so no-longer passes this assertion if using a version of redis-py with this change... A simple fix would probably be to just zap this line, it doesn't seem to have any super-critical purpose

**Comment by Grokzen** [comment]
@AngusP I merged the MR you posted. Closing this MR but i will try to take a pass over the entire code base to bump this code to the same standard as the latests redis-py code becuase there is more changes that might need to be ported here.
