### ISSUE TITLE
Support for Redis 4.0.2?

### ISSUE THREAD

**Issue by miriaford** [Grokzen/redis-py-cluster#224]
I wonder how well does the current master branch support Redis 4.0.2? I read on the redis official doc that "Redis Cluster 4.0 is not compatible with Redis Cluster 3.2 at cluster bus protocol level". I'm not sure how much does that impact redis-py-cluster.

Thanks!

**Comment by Grokzen** [comment]
@miriaford I do not know really, have not yet tested redis 4.0.x yet so i can't tell. In theory it should not be any difference if there was no changes to how commands is executed to the redis servers. What the bus protocol level thingy means might be that you can't run a cluster with redis 3.2 and 4.0 in the same cluster as the clusters nodes can't talk to each other. The clients should not really be affected by this.

**Comment by Grokzen** [comment]
@miriaford This issue was stated as a question and i answered it in my previous post. I will close this issue as the question was "kinda" answered. When this client is fully reids cluster 4.0.x supported i will add that into the changelog and make a new major release that will support it.
