### ISSUE TITLE
在python2.7 环境中无问题在2.6.6版本中报语法错误

### ISSUE THREAD

**Issue by benben17** [Grokzen/redis-py-cluster#233]
Traceback (most recent call last):
  File "check_redis_status.py", line 7, in <module>
    from rediscluster.nodemanager import NodeManager
  File "/usr/lib/python2.6/site-packages/rediscluster/__init__.py", line 7, in <module>
    from .client import StrictRedisCluster, RedisCluster
  File "/usr/lib/python2.6/site-packages/rediscluster/client.py", line 219
    servers = list({'{0}:{1}'.format(nativestr(info['host']), info['port']) for info in self.connection_pool.nodes.startup_nodes})
                                                                              ^
SyntaxError: invalid syntax

**Comment by Grokzen** [comment]
@benben17 This site uses English as main language, Change your title to be in english and reopen the issue.

**Comment by AngusP** [comment]
Also as shown here http://redis-py-cluster.readthedocs.io/en/master/#supported-python-versions this library supports Python 2.7+, not 2.6.6
