### ISSUE TITLE
AWS Redis Cluster fails with redis.exceptions.ResponseError: MOVED

### ISSUE THREAD

**Issue by mingtm** [Grokzen/redis-py-cluster#236]
Here is my sample code:

```
from rediscluster import StrictRedisCluster
startup_nodes = [{"host": "xxxx.clustercfg.apn2.cache.amazonaws.com", "port": "6379"}]
r = StrictRedisCluster(startup_nodes=startup_nodes, decode_responses=True, skip_full_coverage_check=True)

# multiple set add
loop:
    r.sadd('foo', 'bar')
```

It fails eventually:

```
Traceback (most recent call last):
  File "loadData.py", line 39, in <module>
    r.sadd(key, values)
  File "/Library/Python/2.7/site-packages/redis/client.py", line 1600, in sadd
    return self.execute_command('SADD', name, *values)
  File "/Library/Python/2.7/site-packages/redis/client.py", line 668, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/Library/Python/2.7/site-packages/redis/client.py", line 680, in parse_response
    response = connection.read_response()
  File "/Library/Python/2.7/site-packages/redis/connection.py", line 629, in read_response
    raise response
redis.exceptions.ResponseError: MOVED 4085 10.213.192.152:6379
```

Any idea? I'm using the latest reds-py-cluster version.

**Comment by Grokzen** [comment]
@mingtm Basically what has happened is that the cluster client thinks that it really should send this command to the server that you are trying to talk to. I am not sure why this happens in your case.

This is not a bug in the code but more of a operational issue with IP:PORT problems.

**Comment by Grokzen** [comment]
@mingtm The solution to your problem there is that you are not running through the redis-cluster client class but throught the normal redis-py class and it can't handle the MOVED case properly. I would suggest your have some installation error or some configuration error but if you fix your code it should start to work again properly.

**Comment by dbqlswh** [comment]
@mingtm I have the same problem. How did you solve this?

**Comment by Grokzen** [comment]
@dbqlswh You solve it by not using the Redis class from redis-py but using RedisCluster class from this library
