### ISSUE TITLE
python 2.6 not support? run error!!!!!!

### ISSUE THREAD

**Issue by bywangxp** [Grokzen/redis-py-cluster#245]
from rediscluster import StrictRedisCluster

error!!!:
servers = list({'{0}:{1}'.format(nativestr(info['host']), info['port']) for info in self.connection_pool.nodes.startup_nodes})

**Comment by Grokzen** [comment]
It is not and it never will be supported by this package. Please see docs for supported python versions https://redis-py-cluster.readthedocs.io/en/master/#supported-python-versions

There is some forks that implement python 2.6 support.
