### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by nelz9999** [Grokzen/redis-py-cluster#247]
I'd like to request that a new release be cut. (1.3.4 was just over a year ago!)

More specifically, my interest is in #195 which is in `unstable` right now.

**Comment by ledinhkien** [comment]
Same here, but my interest is in [this commit](https://github.com/Grokzen/redis-py-cluster/commit/b12c3538b3b1c46e7ba7ce9f78c245a80ced5f7f). It would be great to know the timeline when the next patch will be released

**Comment by Grokzen** [comment]
1.3.5 is now out
