### ISSUE TITLE
support write to master and  read from slave

### ISSUE THREAD

**Issue by derek0377** [Grokzen/redis-py-cluster#249]

**Comment by derek0377** [comment]
support write to master and  read from slave
It is common to use the mode, but it is not support yet

**Comment by Grokzen** [comment]
This feature will require some deep rewrite of the routing capability and i can't say when i can spend time on doing this ammount of work for this.

**Comment by Grokzen** [comment]
Currently the way i would reccommend that you try yourself for now is to have 2 client instances in your application. One that runs the normal `ConnectionPool` class and one instance that runs `ClusterReadOnlyConnectionPool`. Then you can route your traffic on your end to the correct instance and get something like the desired write/read capability you are looking for.

**Comment by jeffwidman** [comment]
Related: #271

**Comment by Grokzen** [comment]
This has been resolved in #291
