### ISSUE TITLE
Does execute_command works for the commands implemented in redis-ml module ?

### ISSUE THREAD

**Issue by SrujithPoondla** [Grokzen/redis-py-cluster#254]
Hi, I am loading the redis-ml module using execute_command('LOAD MODULE', 'path to the module). After that when I try to use commands in that module I am getting command not found exception. Do I need to modify anything in the client.py ?

**Comment by SrujithPoondla** [comment]
Few commands are working if I load the module while creating the cluster. Working commands are ML.MATRIX.SET, ML.MATRIX.GET. But ML.MATRIX.ADD not working and throwing the exception `redis.exceptions.ResponseError: WRONGTYPE Operation against a key holding the wrong kind of value`. Does any one have any idea regarding this?

**Comment by Grokzen** [comment]
@SrujithPoondla Can you list all the internal redis methods that redis-ml wants to use from the normal redis lib? Some commands have changed when working in a redis cluster env.

I see one of 4 scenarios why this happens

1. redis-ml uses a normal redis command wrongly by sending in a data structure that it do not support
2. redis-py-cluster have reimplemented a command wrongly
3. redis-ml is not cluster compatible
4. You are using redis-ml wrong

**Comment by Grokzen** [comment]
It would also help if you can post the entire exception and start to dig around if the problem is in redis-ml or in this lib or down the stack inside reids-py itself. Example code for error reproduction could also help.

**Comment by SrujithPoondla** [comment]
Hi @Grokzen  Thanks for the info. Currently, Redis-ML doesn't support cluster. In my case, the error was trying to use ADD command from ml module. But in the cluster scenario, one matrix might be in one node and another in a different node. So it was failing with default ml module. I modified the module to my own use cases with cluster support. It's working now! 👍

**Comment by Grokzen** [comment]
@SrujithPoondla You should try to get support for cluster merged into redis-ml if possible.

**Comment by SrujithPoondla** [comment]
@Grokzen Sure, I will do that sometime this weekend.
