### ISSUE TITLE
Does this work with non-clustered Redis?

### ISSUE THREAD

**Issue by thieman** [Grokzen/redis-py-cluster#263]
I'm looking to port our Redis 2.8 non-clustered instance to Redis 4 clustered. Two questions, I suppose:

1. Does this client work with non-clustered Redis instances?
2. Does this client work with Redis major version 2?

Apologies if this was already answered, I couldn't find it from spelunking in Issues.

**Comment by Grokzen** [comment]
1. No it do not work with a non-clustered instance as this client requires that some cluster commands exists and return proper cluster data. The solution you need if you make a lib or integration is to have settings that will create either a `StrictRedisCluster` class or the normal `StrictRedis` class and then use the same variable name in your code.
2. If you are this unsure about the redis-server requirements i suggest you read up on the cluster specification and documentation over at https://redis.io/topics/cluster-spec . The short answer is no as redis cluster mode was introduced in redis 3.0.0 and is not ported back to redis 2.x

**Comment by thieman** [comment]
Got it, thanks for answering. It's _exclusively_ a client for clustered Redis then, in summary.
