### ISSUE TITLE
ConnectionError while ussing scan_iter

### ISSUE THREAD

**Issue by pabloariasmora** [Grokzen/redis-py-cluster#264]
Hi.

I have a large amount of keys (over 60000) with a similar pattern, and I want to retrieve all of them. So I'm using `scan_iter` function.

Here is the general idea.
```
 for key inrediscluster.scan_iter("pattern:*"):
       print(key)
      # Other heavy operations
```

But the keys that matched are so many, and the code inside the loop is long an heavy that, there are some cases that I received this error, so the execution ends.

```
Traceback (most recent call last):
 File "/usr/lib/python3.4/site-packages/redis/connection.py", line 392, in read_response
   raise socket.error(SERVER_CLOSED_CONNECTION_ERROR)
OSError: Connection closed by server.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "observer.py", line 53, in joborchestrator.status_report.observer.ObserverThread.run
 File "/usr/lib/python3.4/site-packages/rediscluster/client.py", line 639, in scan_iter
   raw_resp = conn.read_response()
 File "/usr/lib/python3.4/site-packages/redis/connection.py", line 624, in read_response
   response = self._parser.read_response()
 File "/usr/lib/python3.4/site-packages/redis/connection.py", line 403, in read_response
   (e.args,))
redis.exceptions.ConnectionError: Error while reading from socket: ('Connection closed by server.',)
```

Is there any that I could do to avoid this, as part of the module configuration? Besides trying to manually reconnect every time that I got the error? Like a retry_amount of times?

Thank
JP

**Comment by Grokzen** [comment]
@pabloariasmora 2 things on this.

First i have never encounterd this kind of error so i am not really sure how to solve this.

Second is that since the connection problem is inside the regular `redis-py` lib i would redirect you there to look for some configuration or solution becuase this lib do not deal with the raw connection parts as `redis-py` already does that for us.

**Comment by pabloariasmora** [comment]
Thanks for the response @Grokzen , and you are right. I'm going to create this Issue on redis-py.
