### ISSUE TITLE
READONLY_MODE does not appear to send reads to read replicas.

### ISSUE THREAD

**Issue by a34729t** [Grokzen/redis-py-cluster#270]
I'm trying to balance reads across a shard, which is supported in Redis Cluster via the `READONLY` command. This library appears to have that included via `readonly_mode`. However, turning on the setting when connecting to a cluster doesn't appear to ever connect to the slave even over a few thousand calls, as measured by `GET` traffic on all the nodes in the shard. A colleague at a major cloud provider also observed this. Is this expected behavior, or are we doing something wrong?

Of note:

- I'm using AWS' Elasticache
- Other libraries with this mode enabled (specifically Lettuce for Java) do send traffic to read replicas. 
- This library (redis-py-cluster) does fine when detecting failovers and moving traffic to the new master, as well as live cluster shard addition and removal.

Here is the script I'm using to test this:

```
from rediscluster import StrictRedisCluster

hostname = "[my cluster]"

def connectToClusterAndGetStuff(i_max=100):
    startup_nodes = [{"host": hostname, "port": "6379"}]
    rc = StrictRedisCluster(startup_nodes=startup_nodes, **readonly_mode=True**, decode_responses=True, skip_full_coverage_check=True)
    for i in range(0, i_max):
        rc.get(i)


for i in range(0, 1000):
    connectToClusterAndGetStuff()
```

**Comment by Grokzen** [comment]
Hi. There is basically a confusion between the difference between readonly in the traditional sense that is redis-py where readonly mode would prohibit the client from sending commands or if it is the server rejecting commands, and the readreplica feature that cluster users want. The connection pool class that is used when `readonly_mode=True` is set was a copy of the same class that existed in redis-py. The intent of it was to mimic the same behaviour as redis-py offered. There is no feature inside redis-py-cluster today that has this readreplica feature. It is something that i want to do, but never got enough time to complete any work for it.

**Comment by a34729t** [comment]
Thank you for the quick reply. Make sense, explanation is appreciated.

**Comment by a34729t** [comment]
I've put together a sketch of how I could see this working: https://github.com/Grokzen/redis-py-cluster/pull/271

**Comment by Grokzen** [comment]
I will close this issue now, and defer this feature that you make in #271 into the issue in #249 as that issue is more descriptive of the real problem and the solution/implementation that you are going for.
