### ISSUE TITLE
pipeline一段时间不使用，再用的时候就会响应很多的None

### ISSUE THREAD

**Issue by hmyixiu** [Grokzen/redis-py-cluster#273]
pipeline一段时间不使用，再用的时候就会响应很多的None

**Comment by holmboe** [comment]
https://translate.google.com/#auto/en/%E6%AE%B5%E6%97%B6%E9%97%B4%E4%B8%8D%E4%BD%BF%E7%94%A8%EF%BC%8C%E5%86%8D%E7%94%A8%E7%9A%84%E6%97%B6%E5%80%99%E5%B0%B1%E4%BC%9A%E5%93%8D%E5%BA%94%E5%BE%88%E5%A4%9A%E7%9A%84

**Comment by holmboe** [comment]
Translates into English:

> The segment time is not used, and it will respond a lot when used again.

**Comment by holmboe** [comment]
@hmyixiu would you care to explain a little more what is the problem? :)

**Comment by hmyixiu** [comment]
Hello holmboe，I am a beginner，thank you very much

when I use StrictRedisCluster to get a pipeline.
eg:
conn = StrictRedisCluster 
conn.pipeline()
pipeline.hmget()
pipeline.hmget()
pipeline.hmget()
....(more commands)
result_list = conn.execute()

usually it is no problem.
but when I don't use it，about after 5 minute，
then I use it again，result_list will have some elements are None

**Comment by Grokzen** [comment]
@hmyixiu Are you saying that you are creating a pipeline object, runs execute on that object, then waits for a few minutes, then try to run execute on that object a second time??
