### ISSUE TITLE
Fails to auto-reconnect when master goes down

### ISSUE THREAD

**Issue by 15astro** [Grokzen/redis-py-cluster#274]
When following code is executed on the cluster with nodes( 3 masters and 3 slaves) and one of the master goes down, the code breaks and does not reconnect:
Redis version: 4.0.11
redis-py-cluster: 1.3.5
```
from rediscluster import StrictRedisCluster as rc
r = rc(startup_nodes=[{"host": "10..0.0.1", "port": "7000"},{"host": "10.0.0.2", "port": "9000"},{"host": "10.0.0.3", "port": "9000"}])
for i in range(1,1000000):
  r.set("b", i)

```
Case 1: CLUSTER FAILOVER

When the cluster failover is executed on the slave of the first node, the above code automatically reconnects to the new master and keep writing data

Case 2: Kill master
When the 1 master is killed, the script brreaks with following error:
```
File "python-batch.py", line 7, in <module>
    r.set("b"+`i`, i)
  File "/usr/lib/python2.7/site-packages/redis/client.py", line 1171, in set
    return self.execute_command('SET', *pieces)
  File "/usr/lib/python2.7/site-packages/rediscluster/utils.py", line 101, in inner
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/rediscluster/client.py", line 403, in execute_command
    raise ClusterError('TTL exhausted.')
rediscluster.exceptions.ClusterError: TTL exhausted.
```
Is there any additional config params required or how this can be handeled without breaking the script which is performing writes? @Grokzen

**Comment by Grokzen** [comment]
It should not be a problem to kill off a running master as redis should handle it to promote a new master and the client should see the problem and correct itself to a good state again. Basically, can you add some prints/debugging information to this part inside the client lib https://github.com/Grokzen/redis-py-cluster/blob/unstable/rediscluster/client.py#L372 and look at what exception you keep getting that is causing you to get TTL exhausted error. My bet would be `except (ConnectionError, TimeoutError):` section, but if that happens then it should try to reconnect to a new node to get a fresh cluster state update based on the failed master.

**Comment by 15astro** [comment]
Yes it is is except (ConnectionError, TimeoutError). It doesn't try to reconnect. Do we need to pass reconnect options somewhere?

**Comment by Grokzen** [comment]
No there is no things like that or config that should solve this problem, the code is designed in such a way to solve this issue by trying to reconnect to a random node in the cluster. When you kill the master node, can you after that see that the cluster has shifted to a correct state with a new promoted master after the initial master was killed? If not then please verify that all hosts in the cluster that you specify in the startup_nodes dict is still reachable.

**Comment by 15astro** [comment]
The new master is elected within a second and all nodes are in connected states including startup_nodes

**Comment by 15astro** [comment]
The node which is killed is in the startup nodes but other two are rechable.

**Comment by Grokzen** [comment]
Stale issue with no input from author for far to long, since not possible to reproduce properly i close this issue now. If there is any update to this issue then please open up a new ticket for this kind of issue.

**Comment by ofhellsfire** [comment]
Hey there,

Got pretty much the same issue, so posting it here. Let me know if you want the fresh one..
I don't get why it can't pick the changed Redis state. Looks like it tries to connect to failed master node.

### Scenario

#### Env

- Linux OS
- Redis Cluster: 3 master + 3 slave nodes that runs via Docker-Compose locally
- python 3.6.10
- redis-py version: 3.5.3
- redis-py-cluster: 2.0.99 (the latest one, RC1)

#### Steps to reproduce

1. Start pretty dumb python script (see the archive in the attachment) which connects to Redis Cluster and sends and gets random messages infinitely: `python rediscluster_failover_test.py`
2. Wait a bit (15-30 seconds)
3. Stop one of masters in the Redis Cluster via `docker-compose -f docker-compose-rediscluster.yaml stop redis-node-<master id>`
4. Make sure your Redis Cluster turns one of slaves to master and RedisCluster status is OK

#### Expected result

Script keeps going

#### Actual result

Script gets stuck and exception is raised after a while: `rediscluster.exceptions.ClusterError: TTL exhausted`
Internally it catches `ConnectionError` 16 times and then `ClusterError: TTL`

#### Additional

Find the docker-compose redis cluster is in the attached archive as well.

Script sample output:

```
$ python rediscluster_failover_test.py                                 
Set key: 810b9260-7c38-42d9-845f-88f15f21750b with value rpzzetbihsgksyqycoznaqiqkkpurtoqrlxlfmofzwkpfyrzrltzhkkdvjxeoxtsc
Get key: 810b9260-7c38-42d9-845f-88f15f21750b :: Value = rpzzetbihsgksyqycoznaqiqkkpurtoqrlxlfmofzwkpfyrzrltzhkkdvjxeoxtsc
Set key: c07fb565-40c1-485c-8fdd-c8236bf21724 with value ztckhwermcsxkcycoyfzoawotimvitrjayolfuodeqmmd
Get key: c07fb565-40c1-485c-8fdd-c8236bf21724 :: Value = ztckhwermcsxkcycoyfzoawotimvitrjayolfuodeqmmd
Set key: 3ca32b14-cc0d-4b25-9ad6-00e7777f15c5 with value wshjjimrfsfuzdclnxdrboifpuixcicssxxmafsllkfignmjaxzbjzurtvdzsdrqeiqviaqiqiahpagrignxjglsndqlxkccphuzkblszyephyzp
Get key: 3ca32b14-cc0d-4b25-9ad6-00e7777f15c5 :: Value = wshjjimrfsfuzdclnxdrboifpuixcicssxxmafsllkfignmjaxzbjzurtvdzsdrqeiqviaqiqiahpagrignxjglsndqlxkccphuzkblszyephyzp
Traceback (most recent call last):
  File "rediscluster_failover_test.py", line 25, in <module>
    rc.set(key, msg)
  File "/home/venv/lib/python3.6/site-packages/redis/client.py", line 1801, in set
    return self.execute_command('SET', *pieces)
  File "/home/venv/lib/python3.6/site-packages/rediscluster/client.py", line 531, in execute_command
    return self._execute_command(*args, **kwargs)
  File "/home/venv/lib/python3.6/site-packages/rediscluster/client.py", line 652, in _execute_command
    raise ClusterError('TTL exhausted.')
rediscluster.exceptions.ClusterError: TTL exhausted.
```
[redis_failover_issue.zip](https://github.com/Grokzen/redis-py-cluster/files/4989387/redis_failover_issue.zip)
