### ISSUE TITLE
KeyError when using StrictRedisCluster.from_url with startup_nodes

### ISSUE THREAD

**Issue by yzf** [Grokzen/redis-py-cluster#279]
when using StrictRedisCluster.from_url with startup_nodes, it will lead to KeyError, because when constructing of startup_nodes, `connection = self.connection_class(host=node["host"], port=node["port"], **self.connection_kwargs)`, the self.connection_kwargs already has `host` and `port` arguement in it, simple example as below:

```
from rediscluster import StrictRedisCluster


startup_nodes = [{'host': '172.17.0.2', 'port': 7000}, {'host': '172.17.0.2', 'port': 7001}]
rc = StrictRedisCluster.from_url(
    url='redis://172.17.0.2:7000',
    decode_responses=True,
    startup_nodes=startup_nodes,
)

print(rc.get('name'))
```

**Comment by allen1106** [comment]
How is this issue now?

```
    def make_connection(self, node):
        """
        Create a new connection
        """
        if self.count_all_num_connections(node) >= self.max_connections:
            if self.max_connections_per_node:
                raise RedisClusterException("Too many connection ({0}) for node: {1}".format(self.count_all_num_connections(node), node['name']))

            raise RedisClusterException("Too many connections")

        self._created_connections_per_node.setdefault(node['name'], 0)
        self._created_connections_per_node[node['name']] += 1
        self.connection_kwargs.pop("host")
        self.connection_kwargs.pop("port")
        connection = self.connection_class(host=node["host"], port=node["port"], **self.connection_kwargs)

        # Must store node in the connection to make it eaiser to track
        connection.node = node

        return connection
```
I found the 'KeyError' is cause of this line, `connection = self.connection_class(host=node["host"], port=node["port"], **self.connection_kwargs)`, self.connection_kwargs has key 'host' and key 'port' as well. So they are in conflict.

I tried to fix like this:
![image](https://user-images.githubusercontent.com/29798757/74713197-09549700-5263-11ea-9b55-d0a519128606.png)
It works well. But I'm not sure if it's a good way.

**Comment by allen1106** [comment]
> How is this issue now?
> 
> ```
>     def make_connection(self, node):
>         """
>         Create a new connection
>         """
>         if self.count_all_num_connections(node) >= self.max_connections:
>             if self.max_connections_per_node:
>                 raise RedisClusterException("Too many connection ({0}) for node: {1}".format(self.count_all_num_connections(node), node['name']))
> 
>             raise RedisClusterException("Too many connections")
> 
>         self._created_connections_per_node.setdefault(node['name'], 0)
>         self._created_connections_per_node[node['name']] += 1
>         self.connection_kwargs.pop("host")
>         self.connection_kwargs.pop("port")
>         connection = self.connection_class(host=node["host"], port=node["port"], **self.connection_kwargs)
> 
>         # Must store node in the connection to make it eaiser to track
>         connection.node = node
> 
>         return connection
> ```
> 
> I found the 'KeyError' is cause of this line, `connection = self.connection_class(host=node["host"], port=node["port"], **self.connection_kwargs)`, self.connection_kwargs has key 'host' and key 'port' as well. So they are in conflict.
> 
> I tried to fix like this:
> ![image](https://user-images.githubusercontent.com/29798757/74713197-09549700-5263-11ea-9b55-d0a519128606.png)
> It works well. But I'm not sure if it's a good way.

![image](https://user-images.githubusercontent.com/29798757/74815624-8c91ed80-5334-11ea-8abe-8e3431ec188c.png)

Maybe we can add some code here, like this:
![image](https://user-images.githubusercontent.com/29798757/74815828-e7c3e000-5334-11ea-8891-1b3c9f662d3b.png)

I think, We don't need the host & port from url as long as there is startup_nodes param.

**Comment by Grokzen** [comment]
@yzf @allen1106 Hi. I have been looking through this issue and my conclusion and decision is that using startup_nodes when using `from_url` is the wrong way of using that classmethod. As it currently stands, i will not put in a fix for this. If you have a set of startupnodes then use the normal class constructor, if you have an URL to use, use that.
I will however put an idea in the backlog where i think that adding an option to the normal startup_nodes where you can specify `{'url': 'redis://127.0.0.1:7000'}` might be an idea worth exploring to bridge these two features nicely.

**Comment by jl-DaDar** [comment]
I am getting this error on django
