### ISSUE TITLE
HSet method hanging

### ISSUE THREAD

**Issue by leon-lee-jl** [Grokzen/redis-py-cluster#280]
I'm trying to use hset command, but it hangs there all the time. Here is my code, 

startup_nodes = [
    {"host": "XX.XX.XX.XX", "port": 6379},
    {"host": "XX.XX.XX.XX", "port": 6379},
    {"host": "XX.XX.XX.XX", "port": 6379},
]
redis = StrictRedisCluster(startup_nodes=startup_nodes, decode_responses=True)

for data in datalist:
    redis.hset("hashname", data.lower(), data)

Any ideas?

**Comment by Grokzen** [comment]
Not really, you need to dig further to see where it gets stuck. If the code is stuck on the client side or not. At least check if the command is reaching the server side or not, try to run MONITOR on all nodes and see if the client recieves the command. If you find a spot where it is stuck on client side then you need to post and show where. The client should not just get stuck like this, maybe investigate if a timeout can be set and if that unblocks your client.

**Comment by leon-lee-jl** [comment]
Thanks for your reply. But I can use set and get command, I don't think I got blocked.

**Comment by Grokzen** [comment]
Just becuase another command path works as you expect, do not mean that a different command path works the exact same way. Please verify on the redis side with the command is recieved by the server, and you need to dig into where the code gets stuck, becuase this is not replicatble in either unittests or in local dev on my side. That basic code works as is.
