### ISSUE TITLE
ClusterConnectionPool.from_url doesn't support ssl

### ISSUE THREAD

**Issue by melinath** [Grokzen/redis-py-cluster#281]
ClusterConnectionPool.from_url supports ssl via the `rediss://` scheme. If that is set, it sets the connection_class for the pool to `SSLConnection`. For clustering to work, this needs to be re-set to `SSLClusterConnection`.

**Comment by Grokzen** [comment]
Hmm, this makes this more messy as i would probably have to take in the entire `from_url` method from the base `ConnectionPool` class. Otherwise i have to do post processing of the class choice if that is possible to switch over to `SSLClusterConnection`

**Comment by Grokzen** [comment]
@melinath Linked commit should sort this problem out. Will be part of next major release
