### ISSUE TITLE
Add link to the RTD docs in the project about me

### ISSUE THREAD

**Issue by jeffwidman** [Grokzen/redis-py-cluster#285]
I know the Readme prominently lists it, but it'd still be convenient to have the RTD linked to in the project's github description right up top... for example, see how we did it in `factory_boy`'s repo: https://github.com/FactoryBoy/factory_boy

![image](https://user-images.githubusercontent.com/483314/47000665-9753c700-d0dd-11e8-82fb-3fd6fdcf06f8.png)

**Comment by Grokzen** [comment]
Added the link to the repo
