### ISSUE TITLE
50% performance / throughput degradation after upgrading from 1.0.0 to 1.3.5

### ISSUE THREAD

**Issue by jeffwidman** [Grokzen/redis-py-cluster#286]
We recently upgraded the version of `redis-py-cluster` used by one of our services from `1.0.0` to `1.3.5` and saw a large performance hit. The following graphs show what happened when we reverted back to `1.0.0`:
1. CPU usage increased by 10% and Memory usage increased by 40%. This graph shows what happened when we reverted back to `1.0.0`:

![image](https://user-images.githubusercontent.com/483314/47000077-498a8f00-d0dc-11e8-8029-4919a38c9a93.png)

2. Throughput of the service decreased by 50% (again, graph shows performance improve after reverting)

![image](https://user-images.githubusercontent.com/483314/47000069-41325400-d0dc-11e8-8931-46e9674949b8.png)

The team working on this has not had time to profile the code further yet. I asked them to run their code under `cProfile` but AFAIK that only provides CPU stats and not memory stats. We'll see what they come back with.

I know you mentioned [the pipeline class got a major rewrite in 1.3.1](https://github.com/Grokzen/redis-py-cluster/issues/155#issuecomment-260146822), do you think that might have contributed to it?

**Comment by Grokzen** [comment]
Interesting indeed. If you have data on the usage patterns of what commands you are using mostly it would help to narrow down the code paths you are using the most.

I checked the diff between 1.0.0..HEAD and what i found out was that i would not be super surprised about the 10% cpu increase. There was some work done mainly in the `execute_command` function that could cause that increase. There is also some additional code in the nodemanager and connection classes that could help to contribute to things. `Nodemanager.encode()` could be it as well.

If you are using pipelines in that dataset you posted above, i am sure that some of the cpu increase is from the big rewrite that took place a while back.

But i am more interested in the memory problem you are seeing. An 40% increase with the same code is a major bump in the overhead. I would try to focus on this part to see where the difference is. But same here, i would need to have a narrow down of what types of commands you are using and to what scale you are using them as that could help me to look into the code on my end as well to see if there is some major issue or major new object allocation that is happening.

**Comment by jeffwidman** [comment]
One thing I realized is that we bumped both `redis-py` (2.10.3-->2.10.6) and `redis-py-cluster` (1.0.0-->1.3.5) and also added `hiredis` (None-->0.2.0), so we need to isolate whether it's truly in `redis-py-cluster`. 

Let me do some further black box testing to see which version bumps it before diving into the actual code.

**Comment by Grokzen** [comment]
@jeffwidman Any update on this issue?

**Comment by Grokzen** [comment]
Closing due to long term inactivity. I personally do not have sucha production envrionment setup like you have here @jeffwidman so i can't really test this out myself either. If you ever find out what the issue is and what is causing this behaviour, please either reopen this issue, or open a new issue with new information about the issue.

**Comment by jeffwidman** [comment]
My apologies, I am no longer supporting this particular team, so can't repro it. I kept meaning to get back to this, but was unable to.

**Comment by Grokzen** [comment]
@jeffwidman Do you remember anything about the general usage pattern that you wore doing? Was it mostly simple get/set operations, how many ops? general size of the cluster and how much data in it? I might be able to setup and test it myself if i get the general parameterrs of the problem.

**Comment by jeffwidman** [comment]
To be honest, it was/is a complete mess... so many levels of wrapping in that code that when the team told me the only perf degradation was flipping between the versions, I didn't exactly believe them--too easy for there to be other side effects. That's why I was planning to directly experiment myself, as well as use `pyspy` to track where the time was actually being spent. It's not worth it... the better thing is to just do some various tests and see where `pyspy` shows time being spent and see if anything jumps out at you.

**Comment by Grokzen** [comment]
Yeah what i guessed is that it can't only have been you guys that noticed that major of a slowdown, it should have been reported plenty more by other people with sucha big degredation of performance. But a performance degredation is what you go in for when you go into a redis cluster by default, there will be overhead that you can't avoid, but there has always been more and more complexity and more calls on the stack for each release so i am not surprised in reality, just the severity of the reported problem was schocking. But unless there will be some other reports with more data to dig deeper into, i will not think about it really.
