### ISSUE TITLE
Update codebase to work with redis-py 3.0.0

### ISSUE THREAD

**Issue by Grokzen** [Grokzen/redis-py-cluster#295]
The latest release of redis-py 3.0.0 have several major breaking changes that needs to be ported and verified in this repo. For now the 1.3.x track will only support 2.10.6 and the plans is that when 1.4.0 is out it will only work with redis-py 3.0.0. If redis-py continues to support the 2.x version line the 1.3.x track in this repo will keep it supported.

**Comment by caiohenriquesilva** [comment]
The problem is the requirements file that is installing the equal or major version than 2.10.6 imo. In my project requirements I had to force the 2.10.6 installation for redis to redis-py-cluster works.

**Comment by Grokzen** [comment]
@caiohenriquesilva I do not get what you mean? The latest release 1.3.6 solved this issue by hardcoding the dependency to `==2.10.6` to solve the root cause of it. That has nothing really todo with this issue right now as the immediate problem was solved.

**Comment by CheViana** [comment]
would love this released asap & ready to help

**Comment by BRIDGE-AI** [comment]
is this on going?
I'd like to get the status of this, plz.

**Comment by Grokzen** [comment]
Release 2.0.0 is done and published
