### ISSUE TITLE
NOAUTH authentication

### ISSUE THREAD

**Issue by 565264946** [Grokzen/redis-py-cluster#297]
hello ,how to use StrictRedisCluster() if redis-cluster has password?  the traker message: redis.exception.ResponseError:NOAUTH authentication required

**Comment by Grokzen** [comment]
@565264946 See the example file https://github.com/Grokzen/redis-py-cluster/blob/unstable/examples/basic_password_protected.py for how to use the cluster client with passwords.

**Comment by 565264946** [comment]
I adopt your advice but a new problem : redis ERR This instance has cluster support disabled ; i use redis-py-cluster is 1.3.5 and redis is 2.10.6

**Comment by Grokzen** [comment]
Do your redis server have cluster mode enabled? If not then read up on some redis cluster tutorial or the official docs at redis.io before you continue to use this client.

**Comment by 565264946** [comment]
can you tell me this cod can use in sentinel redis cluster or mater-slave redis cluster ?

**Comment by Grokzen** [comment]
The docs say `This client provides a client for redis cluster that was added in redis 3.0.`

The `redis-py` client provides everything you need to run a sentinel cluster. This client provides everything else you need to run a proper redis-cluster.

**Comment by zhesiBomb** [comment]
https://github.com/Grokzen/redis-py-cluster/blob/unstable/examples/basic_password_protected.py , 404
I need your help. Thank you

**Comment by zhesiBomb** [comment]
I know how to solve this problem
