### ISSUE TITLE
Why are we not using Redis's own rename() command?

### ISSUE THREAD

**Issue by vivekfantain** [Grokzen/redis-py-cluster#299]
https://github.com/Grokzen/redis-py-cluster/blob/01e2c4632f469b4567e47712add0bfaaceaa2830/rediscluster/client.py#L729

I am seeing this code try to download the entire data and upload it.  I get it that this is needed if the data is across nodes.  But this does cause memory / performance issues if the data Is large.  Is there a way to ensure that we can use the Redis internal rename command if we know that the keys belong to the same slot?

**Comment by vivekfantain** [comment]
The reason why I raised an issue, the current rename crashes every so often because the dump() command internally is causing unicode errors.  So this approach of dumping it to client and pushing it back to the other node is not quite without issues.

**Comment by Grokzen** [comment]
Can you provide a reproducable example of loading the data, then using the command to get an error? Also that issue is really a seperate issue from the original question. If you want to move keys from one slot to another the propsed change would not help there as you would still need to jump to the client first.

**Comment by Grokzen** [comment]
@vivekfantain I pushed a improvement to the unstable branch now where if both keys for rename is in the same slot then it will send up rename to the node. If there is a crossslot error then it will use the fallback method of downoading and uploading the keys. Not optimal, but a bit better at least.

**Comment by Grokzen** [comment]
Closing feature as resolved/done and included in next major release.
