### ISSUE TITLE
ERROR sending 'cluster slots' command to redis server

### ISSUE THREAD

**Issue by damonLL** [Grokzen/redis-py-cluster#312]
I believe this is a new instance of an old behavior.

redis-py-cluster version 1.3.6
Python version 2.7
Redis version 5.0.3

Running AWS ElastiCache with cluster-mode-enabled turned on.

Having connected to the configuration server, and each of the individual nodes in my multi-shard environment, I can get the results of "CLUSTER SLOTS" from the command line and even through telnet, but I cannot from my Python script. 

Output of redis-cli when I run it:

```
hidden name:6379> CLUSTER SLOTS
1) 1) (integer) 0
   2) (integer) 5461
   3) 1) "172.31.39.203"
      2) (integer) 6379
      3) "unique-id-hidden"
   4) 1) "172.31.37.45"
      2) (integer) 6379
      3) "unique-id-hidden"
   5) 1) "172.31.47.179"
      2) (integer) 6379
      3) "unique-id-hidden"
2) 1) (integer) 5462
   2) (integer) 10922
   3) 1) "172.31.38.8"
      2) (integer) 6379
      3) "unique-id-hidden"
   4) 1) "172.31.47.175"
      2) (integer) 6379
      3) "unique-id-hidden"
   5) 1) "172.31.39.108"
      2) (integer) 6379
      3) "unique-id-hidden"
3) 1) (integer) 10923
   2) (integer) 16383
   3) 1) "172.31.41.171"
      2) (integer) 6379
      3) "unique-id-hidden"
   4) 1) "172.31.43.80"
      2) (integer) 6379
      3) "unique-id-hidden"
   5) 1) "172.31.43.238"
      2) (integer) 6379
      3) "unique-id-hidden"
```

Additionally here is the output of `telnet` performing the same command so you can see the actual Redis protocol (I've removed the hostnames and unique ID's, so the actual length of those fields will probably not match the value expected, but that's because of manual editing)

```

[ec2-user@ip-172-31-43-226 ~]$ telnet my-cluster-name 6379
Trying 172.31.47.179...
Connected to my-cluster-name.
Escape character is '^]'.
CLUSTER SLOTS
*3
*5
:0
:5461
*3
$13
172.31.39.203
:6379
$40
unique-id-hidden 
*3
$12
172.31.37.45
:6379
$40
unique-id-hidden 
*3
$13
172.31.47.179
:6379
$40
unique-id-hidden 
*5
:5462
:10922
*3
$11
172.31.38.8
:6379
$40
unique-id-hidden 
*3
$13
172.31.47.175
:6379
$40
unique-id-hidden 
*3
$13
172.31.39.108
:6379
$40
unique-id-hidden 
*5
:10923
:16383
*3
$13
172.31.41.171
:6379
$40
unique-id-hidden 
*3
$12
172.31.43.80
:6379
$40
unique-id-hidden 
*3
$13
172.31.43.238
:6379
$40
unique-id-hidden 
^]quit

telnet> quit
Connection closed.
```

As you can see both the Redis CLI as well as the telnet version of the command work; however, when I execute the code, I get this:

```
Error: ERROR sending 'cluster slots' command to redis server: [{u'host': u'my-cluster-name', u'port': 6379}]
```

If I can provide additional information please let me know. Any details about the environment will need to be communicated privately, however.

**Comment by damonLL** [comment]
Additionally:  I have ```skip_full_coverage_check=True``` in the configuration of the StrictRedisCluster object as well, hoping that would avoid this, but no luck.

**Comment by damonLL** [comment]
Additional notes:

- All tests were performed from the same client system to the same server system (two linux boxes).
- Was able to successfully connect from the same client and server but with redis-py driver instead of redis-py-cluster driver

I believe all of this rules out any issues with the Redis Server, the network, the client code, and either host. And since the redis-py driver, the CLI command, and the telnet command all connect successfully and print out CLUSTER SLOTS information appropriately (for CLI command and telnet command), I can't think of anything else other than the redis-py-cluster driver having a problem when it sees the ID of the node in the output (similar to an issue you fixed in the past). Perhaps this is a regression?

Thank you for looking into this!

**Comment by damonLL** [comment]
Please disregard. I do not know what I have changed, but it is now working. If I figure out what I was doing wrong initially I will provide detailed information. Thank you!

**Comment by horriblyUnpythonic** [comment]
We had previously been using redis-py version 2.10.3. When we installed redis-py-cluster, it was brought this up to 2.10.6, but our requirements code brought it back down, which doesn't seem to work with redis-py-cluster.
