### ISSUE TITLE
Error configuring cache backend in Django

### ISSUE THREAD

**Issue by engstrom** [Grokzen/redis-py-cluster#314]
Is there a way to use `redis-py-cluster` as a cache backend in Django? I found [this comment in a django-redis issue](https://github.com/niwinz/django-redis/issues/208#issuecomment-352585533) but when I try this with my ElastiCache Redis cluster's configuration endpoint I get this error:

```
rediscluster.exceptions.RedisClusterException: Redis Cluster cannot be connected. Please provide at least one reachable node.
```

**Comment by Grokzen** [comment]
You basically need to be able to get at least one startup cluster node to be sent into the constructor of the RedisCluster client class. https://github.com/Grokzen/redis-py-cluster/blob/unstable/examples/basic.py is a basic example of what is minimally required to connect to a cluster. How you get from here to there? i do not know and that is mostly for the django-redis to deal with.

**Comment by engstrom** [comment]
That makes sense. Thank you.
