### ISSUE TITLE
Move command with a different slot causes a TTL exhausted.

### ISSUE THREAD

**Issue by mat013** [Grokzen/redis-py-cluster#318]
While testing a redis cluster I discovered some strange behaviour, which I am unsure where the bug lies.

The issue is when a move response is returned with another slot than the one decided in the  execute in the StrictRedisCluster:

The issue is the following code snippet in the execute_method in StrictRedisCluster:
    @clusterdown_wrapper
    def execute_command(self, *args, **kwargs):
        ...
a)     slot = self._determine_slot(*args)
        while ttl > 0:
            if asking:
               ...
            else:
                if self.refresh_table_asap:
                    # MOVED
b)                  node = self.connection_pool.get_master_node_by_slot(slot)
                else:
                    node = self.connection_pool.get_node_by_slot(slot)
c)              r = self.connection_pool.get_connection_by_node(node)

            try:
                ...
d)              r.send_command(*args)
e)              return self.parse_response(r, command, **kwargs)
                ...
            except MovedError as e:
                # Reinitialize on ever x number of MovedError.
                # This counter will increase faster when the same client object
                # is shared between multiple threads. To reduce the frequency you
                # can set the variable 'reinitialize_steps' in the constructor.
                self.refresh_table_asap = True
                self.connection_pool.nodes.increment_reinitialize_counter()

f)                node = self.connection_pool.nodes.set_node(e.host, e.port, server_type='master')
g)                self.connection_pool.nodes.slots[e.slot_id][0] = node

What we have seen is follows:

a slot is computed on the client and return let us say slot s1... item a)
node n1 is resolved by mapping the master slot of s1 to a node... item b)
and connection is resolved from n1... item c)
request is sent... item d)
the response is parsed which is a move command with slot s2 and node n2 and an exception is thrown ... item e)
a new node n3 will be created with the information from the exception... item f)
the slot n2 is not updated with the n3 node.
and everything is retried again.

The slot is calculated to s1, which then is resolved to n1

What I think should happen is either:

1. s1 should be resolved to n3 
2 the slot variable should be updated to contain the s2 value

What seem quite strange around this is that the server and the client do not compute to the same slot. 

a key which basically is a json string, which contained a lot of curly braces, which may have been the issue. 

But if solution 1 is correct it means that line g: 

self.connection_pool.nodes.slots[e.slot_id][0] = node

has to be corrected to self.connection_pool.nodes.slots[slot_id][0] = node

If solution 2 is correct 
Then following line should be added after g:
                slot = e.slot_id

I am unsure if one should follow what the server responds or the client should follow what it has?

**Comment by Grokzen** [comment]
Basically, without any solid steps to reproduce the problem and what data/state your cluster was in before the problem and after the problem, i will have a hard time to really determine anything of this as i assume as the code is right now it works as expected and that it does correct and that your end have got into a wired state or edge case that was not intended to be in, so without the cluster state at least before and after your moved error started to happen, i can't really say anything. You might have some wired case of splitbrain that caused this, i dunno really.

**Comment by mat013** [comment]
Hi 

The cluster was rebooted and the hash slot was was not matching between the server and the client. So it is already from the server starts.

I have submitted a bug to https://github.com/antirez/redis/issues/6027

However I think the python library could be improved by taking into the account the that the slot has been moved to another node, and thereby be more robust and save a round trip.

Enterprise redis 5.4.0-19 has been used for the cluster

In order to reproduce the issue:

Restart a new cluster 

Execute following script:

        client = StrictRedisCluster.from_url(url="redis://redis-xx:13893")
        client.set("{'1':{'i32':1}}", "a")

Actual result: rediscluster.exceptions.ClusterError: TTL exhausted. is thrown

Expected result: The client is trying to use the other slot, which the server has been indicated is the right slot, and the operation was applied to that server and no exception occurred

**Comment by Grokzen** [comment]
@mat013 As i mentioned in the linked issue i do think that the problem is with Redis Enterprise as i have reviewed the keyslot algorithm i have here and it is according to spec and performs as i expect and according to the spec. You need to get this problem cross verified that it is an issue with Enterprise Redis as i do not think it is a problem with this lib.

**Comment by Grokzen** [comment]
Also on a technical side-note. Nothing but vanilla redis is "officially" supported. Yes if you follow the ABI/API of redis is shold work, but we probably have proof here that it do not.

**Comment by mat013** [comment]
But even though the problem has not been reproducable in the community edition of Redis IMHO I think that rather than raising a TTL exhausted exception(which IMHO is not correct because the server has indicated that another node should be used, however the client never tries the other node) the behaviour of the library could be improved as the redis protocol actually supports trying another server also in case that the hash_slot is not agreed between the client and server.

If the line is added as suggested i.e. 
slot = e.slot_id

 I would think the library would work in both cases i.e. when the hash_slot is agreed between the client and the server and when it not agreed. 

So why not support both cases because protocol actually leaves the possibility.

I would be happy to make a PR if you think this would be an improvement

**Comment by Grokzen** [comment]
No the behaviour of the library is Correct as it tries to determine the hash of the slot and it gets the slot number that the spec and vanilla redis says it should be, see my reproduce in the redis ticket. The lib gets the same slots as the redis server outputs.

The TTL exchausted is a consequence of a missmatch between what the cluster says is a MOVED error and what the client thinks is right. And even if i change it to trust what the cluster says is true, it will still fail out as the client lib will not magically change what slot it thinks the key belongs to. And the client lib should not save any data on what key is routed to what node. It should save the node layout yes, but not some magic rebind table that a keyslot output from this lib should be translated to something that the server side says.

Please do try to add that line you have and make some tests to prove me wrong, then i will consider it, but i need proof of it first that that kind of change really works in both cases.

But i still argue/stand that your redis server is the problem, not the lib and the server should correct it's fault to comply with the spec.

**Comment by mat013** [comment]
I agree it the problem is on the server, and I have submitted a bug. But as it stands right now I do not think you can work around the issue  unless the mapping between the hash slot and nodes are modified manually, which I thin would be a hack

I will need a colleague of mine to do the test it as I do not have the necessary access, and I am effectively on holiday so it may take 3 weekhowever I can give concrete examples when it fails and what would fix it and how it will work when adding the fix, 

My fix makes the assumption that the MOVE operation whenever the client and the server both agree 
on the hash_slot then that will be returned as part of the MOVE response, but I think that would be a fair assumption.

So given the code is as follow:

a) slot = self._determine_slot(*args)
while ttl > 0:
if asking:
...
else:
if self.refresh_table_asap:
# MOVED
b) node = self.connection_pool.get_master_node_by_slot(slot)
else:
node = self.connection_pool.get_node_by_slot(slot)
c) r = self.connection_pool.get_connection_by_node(node)

        try:
            ...
d) r.send_command(*args)
e) return self.parse_response(r, command, **kwargs)
...
except MovedError as e:
# Reinitialize on ever x number of MovedError.
# This counter will increase faster when the same client object
# is shared between multiple threads. To reduce the frequency you
# can set the variable 'reinitialize_steps' in the constructor.
self.refresh_table_asap = True
self.connection_pool.nodes.increment_reinitialize_counter()

f) node = self.connection_pool.nodes.set_node(e.host, e.port, server_type='master')
g) self.connection_pool.nodes.slots[e.slot_id][0] = node
h) **slot = e.slot_id**

Line H is the one I intended to add

Supposedly we do not have line H and given we have two nodes one having 100.100.100.100 and the other 200.200.200.200

The mapping between hash slot to node used in line b) is 

...
[10000] = 100.100.100.100.100
[20000] = 100.100.100.100.100

We imagine that the correct node for hash_slot 10000 should be on 200.200.200.200 but our for some reason the mapping do not match what is on the server

What we have seen is that following: 

in line a) slot = 10000 
in line b) node = 100.100.100.100
in line c) the connection to 100.100.100.100 is returned
in line d-e) the request is sent and answer is received where a MOVE response has been returned with the port 20000 and 200.200.200.200
in line f) a new node is being created with the ip 200.200.200.200
in line g) the index [20000] is now set to 200.200.200.200

Everything will be repeated until TTL is exhausted because index 20000 is updated but the slot we look at is 10000

If line h) was added then 
In the case client and server agree on the hash slot then

in line a) slot = 10000 
in line b) node = 100.100.100.100
in line c) the connection to 100.100.100.100 is returned
in line d-e) the request is sent and answer is received where a MOVE response has been returned with the port 10000 and 200.200.200.200
in line f) a new node is being created with the ip 200.200.200.200
in line g) the index [10000] is now set to 200.200.200.200
in line h) slot is assigned to 10000 (so effectively the slot did not change)

2nd iteration 

in line a) slot = 10000 
in line b) node = 200.200.200.200
in line c) the connection to 200.200.200.200 is returned
in line d-e) the request is sent and answer is OK


In the case client and server do not agree on the hash slot then

in line a) slot = 10000 
in line b) node = 100.100.100.100
in line c) the connection to 100.100.100.100 is returned
in line d-e) the request is sent and answer is received where a MOVE response has been returned with the port 20000 and 200.200.200.200
in line f) a new node is being created with the ip 200.200.200.200
in line g) the index [20000] is now set to 200.200.200.200
in line h) slot is assigned to 20000 

We do another iteration 

in line a) slot = 20000 
in line b) node = 200.200.200.200
in line c) the connection to 200.200.200.200 is returned
in line d-e) the request is sent and answer is OK
