### ISSUE TITLE
Wrong number of args calling Redis command From Lua script

### ISSUE THREAD

**Issue by jeremyzhou** [Grokzen/redis-py-cluster#319]
**Error print:**
```
Error running script (call to f_d8fc9f4469dc3bea9662f1af23a225c6fbd33622): @user_script:12: @user_script: 12: Wrong number of args calling Redis command From Lua script : ResponseError
Traceback (most recent call last):
File "/var/task/lambda_function.py", line 115, in POSTCheckin
    return checkin(request)
File "/var/task/lambda_function.py", line 147, in checkin
    get_secret_and_expiry(r, auth)
File "/var/task/lambda_function.py", line 315, in get_secret_and_expiry
    int(time.time()), auth["nonce"])
File "/var/task/redis/client.py", line 2067, in eval
    return self.execute_command('EVAL', script, numkeys, *keys_and_args)
File "/var/task/rediscluster/utils.py", line 101, in inner
    return func(*args, **kwargs)
File "/var/task/rediscluster/client.py", line 371, in execute_command
    return self.parse_response(r, command, **kwargs)
File "/var/task/redis/client.py", line 680, in parse_response
    response = connection.read_response()
File "/var/task/redis/connection.py", line 629, in read_response
    raise response
ResponseError: Error running script (call to f_d8fc9f4469dc3bea9662f1af23a225c6fbd33622): 

@user_script:12: @user_script: 12: Wrong number of args calling Redis command From Lua script
```

**code**

```
def create_redis():
    settings = load_env(load_config())
    #return redis.StrictRedis(host=settings["redis"]["host"])
    startup_nodes = [{"host": settings["redis"]["host"], "port": 6379}]
    return RedisCluster(startup_nodes=startup_nodes, skip_full_coverage_check=True)

def get_secret_and_expiry(redis_, auth):
    lua = """
        redis.call("ZREMRANGEBYSCORE", "nonce", 0, ARGV[1] - 900)
        local valid_nonce = redis.call("ZADD", "nonce", "NX", ARGV[1], ARGV[2])
        if valid_nonce ~= 1 then
            return {"ERR", "INVALID_NONCE", "", ""}
        end
        local mac_exists = redis.call("EXISTS", KEYS[1])
        if mac_exists ~= 1 then
            return {"ERR", "DEVICE_NOT_FOUND", "", ""}
        end
        local result = redis.call("GET", KEYS[1], "secret",
                                                    "device_pairing",
                                                    "expiry_time")
        return {"OK", result[1], result[2], result[3]}
    """

    **return redis_.eval(lua, 1, "{device/" + auth["id"].lower()+"}", int(time.time()), auth["nonce"])**
```

**Comment by Grokzen** [comment]
@jeremyzhou If you try to run a lua script that only has the following in it
```
lua = """
  return {}
"""
```

With your code. If you get an error from that basic test case, then it is something wrong on this client code. If you do not get an error from that, you have an issue in your lua code and that i am not able to help with really as i have never used lua towards redis before.

My initial thought is that you have some issue with your lua code and not the redis-py-cluster client code.

**Comment by jeremyzhou** [comment]
@Grokzen hi, Thanks for your reply soon.

These code work in single node mode. Now i had created a redis cluster.
Is code right below?
rediscluster_.eval(lua_script, key_number, key_name, arg1,arg2……)

I will follow your advise to do some test.

**Comment by Grokzen** [comment]
Well what basically you need to debug if i understand the lua thingy correct, is if your arguments that you want to pass down from the redis client down to lua is getting sent down properly or not. It could be that this client lib mangels the arguments in some bad way. Or it could be that the `redis.call()` command works differently in a cluster environment by taking another set or arguments. Also note that eval itself might work differently from the client pov just becuase eval is not super compatible with a clustered envrionment as you have no idea to what node you really want to send your lua code to be executed. I think it sends to the node that the first key maps to or somethiing.

Ping back when you have done some more debugging to see if you can locate where the issue is first.

**Comment by jeremyzhou** [comment]
@Grokzen 
Thanks for your help. Can you show me how to use command hmset with your lib?

I will use reids lib command hmset to store the info in another function. but i can not use reidscluster lib  command hmset in cluster mode. 
so i had changed hmset to set. the key type had change from hset to string.
That's the reason why lua scirpt fialed.

257) "{device/18:b1:69:00:00:59}"
dev-cluster.clustercfg.use2.cache.amazonaws.com:6379> get {device/18:b1:69:00:03:22} secret
(error) ERR wrong number of arguments for 'get' command
dev-cluster.clustercfg.use2.cache.amazonaws.com:6379> GET {device/18:b1:69:00:03:22} secret
(error) ERR wrong number of arguments for 'get' command
dev-cluster.clustercfg.use2.cache.amazonaws.com:6379> HGET {device/18:b1:69:00:03:22} secret
(error) WRONGTYPE Operation against a key holding the wrong kind of value
dev-cluster.clustercfg.use2.cache.amazonaws.com:6379> HMGET {device/18:b1:69:00:03:22} secret
(error) WRONGTYPE Operation against a key holding the wrong kind of value
dev-cluster.clustercfg.use2.cache.amazonaws.com:6379> type {device/18:b1:69:00:03:22}
string

**Comment by Grokzen** [comment]
Your problem is that you have a space between the `{...}` and `secret`. It shold be `get {device/18:b1:69:00:03:22}secret`

**Comment by Grokzen** [comment]
Read up on hashkeys here before you continue to use that feature https://redis.io/topics/cluster-spec#keys-hash-tags

**Comment by jeremyzhou** [comment]
secret is one field of this key.

dev-cluster.clustercfg.use2.cache.amazonaws.com:6379> get {device/18:b1:69:00:03:22}secret
(nil)
dev-cluster.clustercfg.use2.cache.amazonaws.com:6379> get {device/18:b1:69:00:03:22} secret
(error) ERR wrong number of arguments for 'get' command
dev-cluster.clustercfg.use2.cache.amazonaws.com:6379> get {device/18:b1:69:00:03:22}
"{'config_version': 1643010725L, 'expiry_time': 1562630400, 'checkin_reply': 'eyIvYXBpL3dpcmVsZXNzL3JhZGlvcy81ZyI6IHsianNvbiI6IHsiYWR2YW5jZWQiOiB7ImJlYWNvbkludGVydmFsIjogMTAwLCAicnRzVGhyZXNob2xkIjogMjM0NiwgImFpcnRpbWVGYWlybmVzcyI6IGZhbHNlLCAibWF4Q2xpZW50cyI6IDMyLCAiZGF0YVJhdGUiOiAiYmVzdCIsICJyc3NpVGhyZXNob2xkIjogLTk1LCAiaW5hY3Rpdml0eVRpbWVvdXQiOiAzMDAsICJ0cmFuc21pdFBvd2VyIjogIkZVTEwifSwgInJhZGlvU2V0dGluZ3MiOiB7InNob3J0R3VhcmRJbnRlcnZhbCI6IHRydWUsICJyYWRpb0JhbmQiOiAiQVVUTyIsICJwcmltYXJ5Q2hhbm5lbCI6IDAsICJhZ2dyZWdhdGlvbiI6IHRydWUsICJlbmFibGVSYWRpbyI6IHRydWUsICJtb2RlIjogIkFDTiJ9fSwgIm1ldGhvZCI6ICJwb3N0In0sICIvYXBpL25ldHdvcmsvaW50ZXJmYWNlcyI6IHsianNvbiI6IHt9LCAibWV0aG9kIjogInBvc3QifSwgIi9hcGkvY2xvdWRNZ210L3VwZGF0ZUZpcm13YXJlIjogeyJqc29uIjogeyJyZXRyeV9kdXJhdGlvbiI6IDM2MDAsICJpc19hdXRvIjogdHJ1ZSwgInNjaGVkdWxlIjogWyIwMCAwNyAqICogNyJdfSwgIm1ldGhvZCI6ICJwb3N0In0sICIvYXBpL2xpY2Vuc2UiOiB7Impzb24iOiB7InNhbmRib3giOiB7ImZpbGVzUGVySG91ciI6IDkwMCwgImJ1dkRpc2FibGUiOiBmYWxzZSwgInZlcmRpY3RXYWl0VGltZSI6IDYwLCAia2V5IjogIiIsICJjb25jdXJyZW50IjogMCwgInVybCI6ICIiLCAibWF4VWZ0cExlbiI6IDEwNDg1NzYwLCAidXJsUnVsZVR0bCI6IDYwfSwgImV4cGlyYXRpb24iOiAiMjAxOS8wNy8wOCIsICJsaWNlbnNlIjogIjEifSwgIm1ldGhvZCI6ICJwb3N0In0sICIvYXBpL3dpcmVsZXNzL3ZhcHMvNWciOiB7Impzb24iOiB7InZhcE51bSI6IDEsICJ2YXBFbnRyeSI6IFt7InNzaWQiOiAic29uaWN3YWxsIiwgInNzbHZwbkFsbG93IjogZmFsc2UsICJzc2lkU3VwcHJlc3MiOiBmYWxzZSwgInZhcEFjdGl2ZSI6IHRydWUsICJhY2wiOiB7ImVudHJ5IjogW10sICJtb2RlIjogIkRFTllNQUMiLCAidXNlU3RhdHVzIjogMCwgInJlbW90ZUFjbCI6IGZhbHNlfSwgImNhdHAiOiB7ImVuYWJsZSI6IGZhbHNlLCAiZmlsZU1heFNpemUiOiA1MTIwLCAiZmlsZVR5cGVzIjogWyJwZGYiXSwgImJsb2NrVW50aWxWZXJkaWN0IjogZmFsc2UsICJleGNsdWRlTUQ1IjogW10sICJwcm90b2NvbHMiOiBbImh0dHAiXX0sICJtYXhDbGllbnRzIjogMzIsICJ2bGFuSWQiOiAwLCAiaWVlZTgwMjExciI6IHsiaWVlZTgwMjExckVuYWJsZSI6IGZhbHNlLCAiZnRPdmVyRHNFbmFibGUiOiBmYWxzZSwgIm1peE1vZGVFbmFibGUiOiBmYWxzZX0sICJzZWN1cml0eSI6IHsiYXV0aFR5cGUiOiAiV1BBMlBTSyIsICJ3ZXAiOiB7ImRlZmF1bHRLZXkiOiAxLCAiY2lwaGVyVHlwZSI6ICJOT05FIn0sICJ3cGEiOiB7ImtleUludGVydmFsIjogODY0MDAsICJwbWZPcHRpb24iOiAiRElTQUJMRUQiLCAicGFzc3BocmFzZSI6ICJwYXNzd29yZCIsICJjaXBoZXJUeXBlIjogIkFFUyJ9LCAicmFkaXVzU2VydmVyIjogeyJyZXRyaWVzIjogNCwgInNlcnZlcjFQb3J0IjogMTgxMiwgImludGVydmFsIjogMCwgInNlcnZlcjJJcCI6ICIiLCAic2VydmVyMlNlY3JldCI6ICIiLCAic2VydmVyMlBvcnQiOiAxODEyLCAic2VydmVyMVNlY3JldCI6ICIiLCAic2VydmVyMUlwIjogIiJ9fSwgImNmcyI6IHsiY2F0ZWdvcnkiOiBbMSwgMiwgMywgNCwgNSwgNiwgNywgOCwgOSwgMTAsIDExLCAxMiwgNTldLCAidmlld09ubHkiOiBmYWxzZSwgImVuYWJsZSI6IGZhbHNlLCAid2xpc3QiOiBbXSwgImJsaXN0IjogW119LCAidXVpZCI6ICIxIn1dfSwgIm1ldGhvZCI6ICJwb3N0In0sICIvYXBpL3N5c3RlbS9zZXR0aW5ncyI6IHsianNvbiI6IHsibGVkRW5hYmxlIjogdHJ1ZSwgInN5c3RlbU5hbWUiOiAiU09OSUNXQVZFIDQzMkUgTm9ydGggQW1lcmljYSIsICJhZG1pbk5hbWUiOiAiIiwgImNvdW50cnlDb2RlIjogIlVTIiwgImVhcG9sVmVyc2lvbiI6ICJWMiIsICJibGUiOiB7ImJsZUFkdkVuYWJsZSI6IGZhbHNlLCAiYmVhY29uRW5hYmxlIjogZmFsc2UsICJiZWFjb25VdWlkIjogIiJ9LCAiYXBNb2RlIjogIkJSSURHRSIsICJiYW5kU3RlZXJpbmdNb2RlIjogIkRpc2FibGUiLCAiYXV0b0xvZ291dFRpbWUiOiA2MDAsICJwb2VPdXRFbmFibGUiOiBmYWxzZX0sICJtZXRob2QiOiAicG9zdCJ9LCAiL2FwaS9uZXR3b3JrL3NzbHZwbiI6IHsianNvbiI6IHsiZG9tYWluIjogIiIsICJsM01nbXRFbmFibGUiOiBmYWxzZSwgInNzbHZwblNlcnZlciI6ICIiLCAidXNlciI6ICIiLCAiYXV0b1JlY29ubmVjdCI6IGZhbHNlLCAicGFzc3dvcmQiOiAiIn0sICJtZXRob2QiOiAicG9zdCJ9LCAiL2FwaS9tZXNoIjogeyJqc29uIjogeyJwc2siOiAiNzVjYTczNDVjZjdhNGVmNjg5YTlkMmJhMDFlNDQwZDMiLCAiZW5hYmxlIjogZmFsc2UsICJyYWRpbyI6ICI1RyIsICJzc2lkIjogIjE3MzM5MjUwIiwgInJzc2kiOiAtODB9LCAibWV0aG9kIjogInBvc3QifSwgIi9hcGkvc3lzdGVtL2RpYWdub3N0aWNzIjogeyJqc29uIjogeyJsaW1pdEF1dG9DaGFubmVsIjogZmFsc2UsICJkZnMiOiBmYWxzZX0sICJtZXRob2QiOiAicG9zdCJ9LCAiL2FwaS93aXJlbGVzcy92YXBzLzI0ZyI6IHsianNvbiI6IHsidmFwTnVtIjogMSwgInZhcEVudHJ5IjogW3sic3NpZCI6ICJzb25pY3dhbGwiLCAic3NsdnBuQWxsb3ciOiBmYWxzZSwgInNzaWRTdXBwcmVzcyI6IGZhbHNlLCAidmFwQWN0aXZlIjogdHJ1ZSwgImFjbCI6IHsiZW50cnkiOiBbXSwgIm1vZGUiOiAiREVOWU1BQyIsICJ1c2VTdGF0dXMiOiAwLCAicmVtb3RlQWNsIjogZmFsc2V9LCAiY2F0cCI6IHsiZW5hYmxlIjogZmFsc2UsICJmaWxlTWF4U2l6ZSI6IDUxMjAsICJmaWxlVHlwZXMiOiBbInBkZiJdLCAiYmxvY2tVbnRpbFZlcmRpY3QiOiBmYWxzZSwgImV4Y2x1ZGVNRDUiOiBbXSwgInByb3RvY29scyI6IFsiaHR0cCJdfSwgIm1heENsaWVudHMiOiAzMiwgInZsYW5JZCI6IDAsICJpZWVlODAyMTFyIjogeyJpZWVlODAyMTFyRW5hYmxlIjogZmFsc2UsICJmdE92ZXJEc0VuYWJsZSI6IGZhbHNlLCAibWl4TW9kZUVuYWJsZSI6IGZhbHNlfSwgInNlY3VyaXR5IjogeyJhdXRoVHlwZSI6ICJXUEEyUFNLIiwgIndlcCI6IHsiZGVmYXVsdEtleSI6IDEsICJjaXBoZXJUeXBlIjogIk5PTkUifSwgIndwYSI6IHsia2V5SW50ZXJ2YWwiOiA4NjQwMCwgInBtZk9wdGlvbiI6ICJESVNBQkxFRCIsICJwYXNzcGhyYXNlIjogInBhc3N3b3JkIiwgImNpcGhlclR5cGUiOiAiQUVTIn0sICJyYWRpdXNTZXJ2ZXIiOiB7InJldHJpZXMiOiA0LCAic2VydmVyMVBvcnQiOiAxODEyLCAiaW50ZXJ2YWwiOiAwLCAic2VydmVyMklwIjogIiIsICJzZXJ2ZXIyU2VjcmV0IjogIiIsICJzZXJ2ZXIyUG9ydCI6IDE4MTIsICJzZXJ2ZXIxU2VjcmV0IjogIiIsICJzZXJ2ZXIxSXAiOiAiIn19LCAiY2ZzIjogeyJjYXRlZ29yeSI6IFsxLCAyLCAzLCA0LCA1LCA2LCA3LCA4LCA5LCAxMCwgMTEsIDEyLCA1OV0sICJ2aWV3T25seSI6IGZhbHNlLCAiZW5hYmxlIjogZmFsc2UsICJ3bGlzdCI6IFtdLCAiYmxpc3QiOiBbXX0sICJ1dWlkIjogIjAifV19LCAibWV0aG9kIjogInBvc3QifSwgIi9hcGkvd2lyZWxlc3MvcmFkaW9zLzI0ZyI6IHsianNvbiI6IHsiYWR2YW5jZWQiOiB7ImJlYWNvbkludGVydmFsIjogMTAwLCAicnRzVGhyZXNob2xkIjogMjM0NiwgImFpcnRpbWVGYWlybmVzcyI6IGZhbHNlLCAibWF4Q2xpZW50cyI6IDMyLCAiZGF0YVJhdGUiOiAiYmVzdCIsICJyc3NpVGhyZXNob2xkIjogLTk1LCAiaW5hY3Rpdml0eVRpbWVvdXQiOiAzMDAsICJ0cmFuc21pdFBvd2VyIjogIkZVTEwifSwgInJhZGlvU2V0dGluZ3MiOiB7InNob3J0R3VhcmRJbnRlcnZhbCI6IHRydWUsICJyYWRpb0JhbmQiOiAiQVVUTyIsICJwcmltYXJ5Q2hhbm5lbCI6IDAsICJhZ2dyZWdhdGlvbiI6IHRydWUsICJlbmFibGVSYWRpbyI6IHRydWUsICJzZWNvbmRDaGFubmVsIjogMCwgIm1vZGUiOiAiTkdCIn19LCAibWV0aG9kIjogInBvc3QifX0=', 'secret': 'nkgiN7Y3pCrGg0QlpTGS6oyohYmhliC2', 'diff': '', 'device_pairing': 0}"
dev-cluster.clustercfg.use2.cache.amazonaws.com:6379>

**Comment by Grokzen** [comment]
Well i would not recommend that you post that output here and would suggest you remove it promptly.

**Comment by Grokzen** [comment]
Well... It looks like you have stored a full json blob in a string key in redis. You are probably looking for the Hash functionality https://redis.io/commands#hash where this feature is properly supported. SET/GET commands only do that, they SET and GET stuff. Nothing more, nothing less. It looks to me that you must read up on a more basic redis tutorial to get familiar with the command basics of redis before you continue with this, becuase this is not an issue with the client lib any longer, and this is not the place and i am not the guy to teach you the very basics of redis. There is tons of blog posts and tutorials and documetnation you can read up to get that working properly for you.

**Comment by jeremyzhou** [comment]
@Grokzen Thanks for your help
