### ISSUE TITLE
Read the Docs still uses StrictRedisCluster

### ISSUE THREAD

**Issue by adam-tokarski** [Grokzen/redis-py-cluster#329]
https://redis-py-cluster.readthedocs.io/en/master/ is still suggesting an usage of `StrictRedisCluster`. One can find either in code or in [relase notes](https://github.com/Grokzen/redis-py-cluster/blob/master/docs/release-notes.rst) that it was changed, but it is confusing.
Would be nice to update this documentation too,.

**Comment by Grokzen** [comment]
@adam-tokarski Aparently the old webhooks into read the docs has been broken for a while now. I rebuilt the master copy manually and it look updated and fixed now. I need to dig into how to update the webhooks so it auto updates in the future.

**Comment by adam-tokarski** [comment]
That was quick. Thanks!
