### ISSUE TITLE
ImportError: cannot import name 'bytes' from 'redis._compat'

### ISSUE THREAD

**Issue by yangmingbai** [Grokzen/redis-py-cluster#337]
in nodemanager line 12
from redis._compat import unicode, bytes, long, basestring
there cannot import name 'bytes'  in redis._compat
version:
redis==3.2.0
redis-py-cluster==2.0.0

**Comment by Grokzen** [comment]
@yangmingbai `redis-py-cluster==2.0.0` Only supports `redis>=3.0.0,<3.1.0`

It is not supported to use any redis version above this so if you pull in a higher version of a requirement package you are basically on your own.

redis-py-cluster 2.1.0 will support up to latest version in redis-py 3.3.x series.

**Comment by xiongdahu** [comment]
use python 3.6.4, redis-py 3.0.0 and 3.0.1, met the same issue

**Comment by Grokzen** [comment]
@xiongdahu What redis-py and redis-py-cluster version are you running?

**Comment by n0thing233** [comment]
got this error with redis-py 3.0.1 and redis-py-cluster 3.1.0

**Comment by Grokzen** [comment]
@n0thing233 If you are working inside the correct redis-py versions, then the most commoon issue is that you have a package named redis inside your envrionment and that superseeds the redis version from pypi. If you try to run `import redis` and look what it acccctually imports from disk inside your python envrionment, you should probably see if it tries to import one of your own files or if it tries to import the upstream redis version. This is the case in 99.5% of all cases and most likely yours. If there would have been an issue with upstream or anything, that would have been detected in the unittests long time ago

**Comment by Grokzen** [comment]
@n0thing233 Also note, that redis-py-cluster 2.1.0 (master branch) is not done yet and there might be issues with running older redis-py versions in there as the aim with the latest redis-py-cluster is to increase the min version of redis-py and i do not reccommend to run anything in the 3.0.x series if you are attempting to run the master branch directly.

**Comment by n0thing233** [comment]
Thank you for the details.  I managed to get redis-py-cluster 1.3.6 working
with redis-2.10.6.

**Comment by linzhi** [comment]
I have the same problem  redis-py-cluster 2.0.0 redis-3.5.1

**Comment by Grokzen** [comment]
@linzhi You are using a unsupported versino of redis-py on your version of redis-py-cluster. Please consult the acctuall release that you are using to see what versions of redis that is supported and compatible. https://github.com/Grokzen/redis-py-cluster/blob/2.0.0/README.md
