### ISSUE TITLE
forgotten import in rediscluster/client.py

### ISSUE THREAD

**Issue by denisguzeyev** [Grokzen/redis-py-cluster#352]
in the method _determine_slot() in "if command in ['XREADGROUP', 'XREAD']:"  there is a "Token" that actually appears w/o any declaration. So the "Token" should be declared

**Comment by Grokzen** [comment]
I know about this last Token piece. The Token defenition was removed sometime after redis-py 3.1 i think and all the places where it is used in my code it has to be removed as well. If you look in the commit history, all but this last one has been removed to make the code up to standard for the latest redis-py version. I am a bit surprised that no tests picked it up and threw a not imported error or similar tho. But i will go through all commands individually and manually to test them all out and i am sure i will get to that part and fix it so XREADGROUP and XREAD works out.
