### ISSUE TITLE
redis-py 3.4.1

### ISSUE THREAD

**Issue by DvirDukhan** [Grokzen/redis-py-cluster#355]
Hi, maybe I'm bursting into an open door but `redis-py` [3.4.1 ](https://github.com/andymccurdy/redis-py/releases/tag/3.4.1) was released, while the current `master` branch `requirments.txt` is not allowing version higher than 3.4.0
```
redis>=3.0.0,<3.4.0
```
This can cause issues when trying to set up an environment that requires the installation of `redis-py` and `redis-py-cluster`.
If there isn't anything special needed for `redis-py-cluster` to support redis-py 3.4.1 then I'll PR with the required changes to `requirments.txt`.
Thanks!

**Comment by Grokzen** [comment]
Aha, so they done a new major release. Yes i will update the master branch to allow for redis-py up to 3.4.x releases. But from a compatibility pov i need to investigate what/how much things that is broken and affected in this repo from their upstream changes.
