### ISSUE TITLE
Dependency discrepency

### ISSUE THREAD

**Issue by allyn-psyonix** [Grokzen/redis-py-cluster#359]
The PIP page and the doc site both reference redis dependency as:

redis>=3.0.0,<3.1.0

However, the readme here indicates:

redis-py >=3.0.0, <3.5.0

The lib itself matches the first, so I think the readme here on github needs to be updated.

**Comment by Grokzen** [comment]
Pip and the docs site has the latest stable released versions on it. The master branch is the current latest development WIP. Master reflect the next release that will be done.
