### ISSUE TITLE
Not working with In-Transit Encryption on Aws Elasticache

### ISSUE THREAD

**Issue by jl-DaDar** [Grokzen/redis-py-cluster#369]
Start a cluster with 1 partition and 1 node
default.redis5.0.cluster.on

then 

from rediscluster import RedisCluster
snode = [{"host": "stage-redis-cluster-0001-001.stage-redis-cluster.xxxxxxxx.ape1.cache.amazonaws.com", "port":"6379"}]
client = RedisCluster(startup_nodes=snode, ssl=True, decode_responses=True, skip_full_coverage_check=True)

and it gives me error

rediscluster.exceptions.RedisClusterException: Redis Cluster cannot be connected. Please provide at least one reachable node.

**Comment by jl-DaDar** [comment]
nevermind i found the answer

ssl_cert_reqs='none'

for those who needs it

**Comment by rbharad27** [comment]
@jl-DaDar 
I have a similar setup (AWS redis with ssl enabled), below code does not seem to work

from rediscluster import RedisCluster
startup_nodes = [{"host": "my_host_name", "port": "6379"}]
rds= RedisCluster(startup_nodes=startup_nodes, ssl=True, ssl_cert_reqs=False, password='password', decode_responses=True, skip_full_coverage_check=True)
rds.ping()

Adding ssl_cert_reqs='none'/ssl_cert_reqs=False does not help in my case, It just waits for the connection without any error

Any idea on this ? how did you connect ?

**Comment by mmcclelland1002** [comment]
> @jl-DaDar I have a similar setup (AWS redis with ssl enabled), below code does not seem to work
> 
> from rediscluster import RedisCluster startup_nodes = [{"host": "my_host_name", "port": "6379"}] rds= RedisCluster(startup_nodes=startup_nodes, ssl=True, ssl_cert_reqs=False, password='password', decode_responses=True, skip_full_coverage_check=True) rds.ping()
> 
> Adding ssl_cert_reqs='none'/ssl_cert_reqs=False does not help in my case, It just waits for the connection without any error
> 
> Any idea on this ? how did you connect ?

any luck? i've run into a similar issue
