### ISSUE TITLE
mget too slow

### ISSUE THREAD

**Issue by yangjiaronga** [Grokzen/redis-py-cluster#375]
MGET is used extensively in projects

 Cluster impl:
      Itterate all keys and send GET for each key.
      This will go alot slower than a normal mget call in StrictRedis.

Is there any good way to optimize it?

**Comment by Grokzen** [comment]
The only way to optimize it would be to make MGET commands to each slot, but even that would not be an optimization as it is per slot and not per node as you host more slots per node then what you have nodes.

So MGET has a very different spread in the efficiency of how much it can be optimized as in the best case scenario, all of your MGET keys is split into 1 slot and  you would have the same performance as a single redis-server instance. And in the worst case scenario you need to split up N number of keys into N different MGET operations as they are in N different number of slots and in that case you have 0 performance gains over simply issuing simple GET commands for each key no matter where they are in your cluster. And you even face a bigger problem with optimizing it or acctually seeing any gains as you have a big overhead of running a cluster client where you need to figure out which slot each key belongs to and then to route it correctly within the cluster client which all adds up to a  loss in the client layer that you need to have a lot of keys in your MGET to acctually gain any performance from MGET in a clustered envrionments.

Based on all of these things, when i did the first implementation of MGET way back when, it was more important that the calling interface and behaviour was preserved over any performance gains that could be achived from the method implementation.
