### ISSUE TITLE
How to use eval method, could you provide a example?

### ISSUE THREAD

**Issue by kenton18** [Grokzen/redis-py-cluster#380]
```
"if (redis.call('exists', KEYS[1]) == 0) then " +
                    "redis.call('hincrby', KEYS[1], ARGV[2], 1); " +
                    "redis.call('pexpire', KEYS[1], ARGV[1]); " +
                    "return nil; " +
                    "end; " +
                "if (redis.call('hexists', KEYS[1], ARGV[2]) == 1) then " +
                    "redis.call('hincrby', KEYS[1], ARGV[2], 1); " +
                    "redis.call('pexpire', KEYS[1], ARGV[1]); " +
                    "return nil; " +
                    "end; " +
                "return redis.call('pttl', KEYS[1]);"
```
I am try to run this scrip with eval() method, but I am not sure what type  keys_and_args exactly is. Here I try to execute a Lua script. Could you provide a complete example?  Thank you so much!
the KEYS[1] should be a key name
the ARGV[2] is a value 
the ARGV[1] is a expire time

**Comment by Grokzen** [comment]
@kenton18 No i do not provide examples/help in how to design regular redis code or solutions to problems. Please try to submit it to stackoverflow or similar site for general assistance into how eval() method works and how to design solutions around it. This issues tracker is only for issues that revolves around problems with this library.
