### ISSUE TITLE
Return values of SET and DELETE operations and their reliable usage.

### ISSUE THREAD

**Issue by adityakapre2009** [Grokzen/redis-py-cluster#382]
I am using `StrictRedisCluster` from this library as redis client. I have observed few things which I could not find in the documentation [here](https://redis-py-cluster.readthedocs.io/en/master/commands.html). 

1. `set` operation returns boolean values. Can we rely on this for checking success/failure of the operation? i.e True for success and False failure of `set`? The redis core [documentation](https://redis.io/commands/set) has different return values though. 

2. `delete` returns `1` for success from what I have observed (Or is it something different like number of keys deleted?). Also I am not sure what it returns in case the command fails or does not delete anything. What would be the response then ? Again, can I use those return values reliably to derive success/failure output of the command.

**Comment by Grokzen** [comment]
@adityakapre2009 

1. There is no override operation done on SET commands to my knowledge. It should use the same method from redis-py and return the same response and data that you should be used to when using that library. If there is an implementation issue with that command then according to spec, submit the error to redis-py and get them to sort it out or explain why it is the way it is right now. There is a translation layer inside redis-py that is responsible for translating the responses defined in the redis client spec that different return values like `OK` and `null` is converted to proper python objects. True/False is good enough and working, and anything else wrong happening and you will get an exception to deal with, that is reliable.

2. DELETE command works according to redis server spec. And the override implementation in a clustered environment simply fullfills the client API so your code works the same way, it is just that the operation is no longer atomic as deleted keys can be in different slots across the cluster.
The spec from redis.io says
```
DEL key [key ...]

...

Return value
Integer reply: The number of keys that were removed.
```
This API to the server is what redis-py and this lib implements properly.
In your delete code on your end, the only two things you can do is to catch an exception or check if the return value matches the number of keys you wanted to delete. Neither clients will provide anything else.
