### ISSUE TITLE
Rc to release on pypi

### ISSUE THREAD

**Issue by alseambusher** [Grokzen/redis-py-cluster#386]
Hi, Do we have a roadmap as to when the current rc is going to be released on pypi as a full release?

Thanks!

**Comment by farzad-xgen** [comment]
Any updates? Celery doesn't support Redis < 3.4 and official 2.0.0 release doesn't work with redis>3.1.0! We manually install from the GitHub repo to make it work but we need to revert to pip installation as soon as the release is ready. Can you give us a time-line for that?

**Comment by asuvorov** [comment]
Hi, Folks...
We are using your awesome Library in our Service, but we have to install it from the `GitHub` Repo `master` Branch, or `2.0.99` Tag, which is not really correct for many Reasons, including Safety and Risk, that any wrong Commit may break our Service too...

So, I have the same Question, as above: is there any Idea, or the Timeline, when `2.1.0` Build will go to `PyPi`?
Thank you...

**Comment by Grokzen** [comment]
I have never done a RC release and published it to pypi, i have seen a few documentation pages on how to do it and not to break any normal users that would not get the RC release downloaded by mistake from me publishing the 2.0.99 release to pypi. I will do some tests on the test.pypi.com site first

**Comment by adaamz** [comment]
You can publish it with different name 😅 eg. py-redis-cluster-rc

**Comment by Grokzen** [comment]
I will drop the RC2 release tonight on pypi properly this time and then i am finishing up the documentation changes i have in the pipeline and then the final release will be made and published.

Also i am closing this issue as it is basically the same content as the existing next release issue #342

**Comment by Grokzen** [comment]
RC2 release has been uploaded to pypi now https://pypi.org/manage/project/redis-py-cluster/release/2.0.99rc2/

To upgrade an existing installation to pre release or install a new environment from scratch you can run the following ` pip install redis-py-cluster redis -U --pre`

Final release will come shortly
