### ISSUE TITLE
some keys set fail

### ISSUE THREAD

**Issue by windyStreet** [Grokzen/redis-py-cluster#426]
python 3.8.2 env 

![image](https://user-images.githubusercontent.com/13999742/104417440-54307900-55b0-11eb-99d2-5ccdc0297bec.png)

when the key set  f1 x3 foo1 etc, run error

**Comment by windyStreet** [comment]
rc = RedisCluster(startup_nodes=startup_nodes, decode_responses=True, password='xxx')

if __name__ == '__main__':
    # print(rc.connection_pool.nodes.nodes)
    rc.set("foo", "bar")
    print(rc.get("foo"))
    # success
    rc.set("foox", "barx")
    print(rc.get("foox"))
    # success
    rc.set("x3", "bar12")
    print(rc.get("x3"))
    # fail key like f1 foo1 x3 ...

#######
#code like this

**Comment by Grokzen** [comment]
@windyStreet This is not enough information. This basic code set works across the board for most ppl. I also need the stack trace that you get when keys fail like you mention. Most likley it is a configuration error in some way on your end.

**Comment by windyStreet** [comment]
yes  ,it's configuer err

cause by : whem i am make the cluster in two server , i used the '127.0.0.1' as member ip 
err like this :
`/usr/local/redis/5.0.2/7004/bin/redis-cli \
--cluster create \
127.0.0.1:7004 \
127.0.0.1:7005 \
192.168.5.109:7006 \
192.168.5.109:7007 \
127.0.0.1:7008 \
192.168.5.109:7004 \
192.168.5.109:7005 \
127.0.0.1:7006 \
127.0.0.1:7007 \
192.168.5.109:7008 \
--cluster-replicas 1  -a xxx`

right mehtod  like this:
/usr/local/redis/5.0.2/7004/bin/redis-cli \
--cluster create \
192.168.5.110:7004 \
192.168.5.110:7005 \
192.168.5.109:7006 \
192.168.5.109:7007 \
192.168.5.110:7008 \
192.168.5.109:7004 \
192.168.5.109:7005 \
192.168.5.110:7006 \
192.168.5.110:7007 \
192.168.5.109:7008 \
--cluster-replicas 1  -a xxx
