### ISSUE TITLE
could I use lrange with pipline?

### ISSUE THREAD

**Issue by ucasiggcas** [Grokzen/redis-py-cluster#431]
hi,dear
when I run the down codes,I got the wrong thing,
```
>>> redis_obj=get_redis()
>>> with redis_obj.pipeline() as pipeline2:
...     key_feat=pipeline2.lrange('kdjdjo',0,100)
... 
>>> key_feat
ClusterPipeline
```
So why is the **ClusterPipeline** ? it should be a list in fact
could you pls help me ?

**Comment by Grokzen** [comment]
@ucasiggcas This section is for reporting issues and not general questions or help. Please reopen this in the `Discussion` tag that you will find to the right of the `Pull Requests` tab.
