### ISSUE TITLE
[Discussion]could I use lrange with pipline ?

### ISSUE THREAD

**Issue by ucasiggcas** [Grokzen/redis-py-cluster#432]
hi,dear
when I run the down codes,I got the wrong thing,

```
>>> redis_obj=get_redis()
>>> with redis_obj.pipeline() as pipeline2:
...     key_feat=pipeline2.lrange('kdjdjo',0,100)
... 
>>> key_feat
ClusterPipeline
```
So why is the ClusterPipeline ? it should be a list in fact
could you pls help me ?

**Comment by Grokzen** [comment]
@ucasiggcas You still open up an issue claiming it as a discussion. There is a separate tab for this in github, please use that and do not open up another discussion issue here as this is for issues and reportable problems/bugs.
