### ISSUE TITLE
ClusterBlockingConnectionPool with default max_connections creates infinite loop

### ISSUE THREAD

**Issue by brocksamson** [Grokzen/redis-py-cluster#435]
ClusterBlockingConnectionPool has max_connections set to None and then inside the _blocking_pool_factory function the system puts None into the LifoQueue until it throws a Full exception.  Unfortunately None or <= 0 for maxsize in a LifoQueue results in an infinite queue size.  So if the max_connections kwarg isn't set when creating this pool, then _blocking_pool_factory runs until the LifoQueue consumes all available memory for your python process.

The fix appears to be rather simple, redis-py defaults max_connections to 50 instead of None in their BlockingConnectionPool class.

**Comment by Grokzen** [comment]
@brocksamson Fixed in above mentioned commit and will be part of 2.1.3 release
