### ISSUE TITLE
Error: rediscluster.exceptions.RedisClusterException: Only 'pubsub' commands can be used by get_connection()

### ISSUE THREAD

**Issue by Shivakumar2602** [Grokzen/redis-py-cluster#459]
Hello Everyone,

I am getting below error while performing the insert in azure redis cache.

```
File \"/home/sh/pipeline/datasketch/lsh.py\", line 317,
in __exit__
    self.close()
  File \"/home/sh/peline/datasketch/lsh.py\", line 320, in close
    self.lsh.keys.empty_buffer()
  File \"/home/sh/pipeline/datasketch/storage.py\", line 1010, in empty_buffer
    self._buffer.execute()
  File \"/home/sh/modelvenv/lib/python3.6/site-packages/redis/client.py\", line 3437, in execute
    self.shard_hint)
  File \"/home/sh/modelvenv/lib/python3.6/site-packages/rediscluster/connection.py\", line 196, in get_connection
    raise RedisClusterException(\"Only 'pubsub' commands can be used by get_connection()\")
rediscluster.exceptions.RedisClusterException: Only 'pubsub' commands can be used by get_connection()

```

version:
redis-py-cluster==2.0.0
python==3.6.9
linux enviornment

RedisCluster connection details:
```
RedisCluster(
    startup_nodes=startup_nodes,
    decode_responses=True,
    skip_full_coverage_check=True,
    password=redis_password,
    ssl=True,
    ssl_cert_reqs='required',
    ssl_ca_certs=path
)
```

Any help will be much appreciated: @Grokzen

**Comment by Grokzen** [comment]
@Shivakumar2602 Are you using some kind of other azure lib ontop of redis-py-cluster to talk to azure redis cache? Also i was not aware of that azure supported managed redis cluster nodes yet?

Also you have some other code that i do not see or understand what you are trying to do really. This `self._buffer.execute()` for example and how you land up down in `get_connection` i do not see either.

I would first recommend that you upgrade to latest redis-py-cluster and try to see if you get the same error. What i expect is that you are running some command that bypasses RedisCluster and goes straight to Redis method, you can see that becuase you go into client.py line 3437 when you do execute before you get into the RedisCluster.execute method. And in there is probably your issue that you have to debug out. I dont know your code so i can't help yo further.

**Comment by Shivakumar2602** [comment]
I am not using any azure lib in my code. I do not know whether azure is providing support for managed redis.

It is erroring out while calling below method in storage.py file:
        def empty_buffer(self):
            self._buffer.execute()
            # To avoid broken pipes, recreate the connection
            # objects upon emptying the buffer
            self.__init__(self.config, name=self._name)

I have upgraded to latest redis-py-cluster version and still getting the same error
One more question I have -- Does datasketch support custom mode azure cache redis cluster.

**Comment by Grokzen** [comment]
@Shivakumar2602 I have no idea what `datasketch` is or how it works or what it supports or not. You have to ask them about this error as this error you are having is not something in my code but in their support for this lib. I do not give direct support to other libs implementing this code base, it is their work to support their code. If you acctually have an issue with the code itself in some case (i do not see a problem in the original message) that is related to the code, please reopen a ticket for that case.
