### ISSUE TITLE
Proposing a PR to fix a few small typos

### ISSUE THREAD

**Issue by timgates42** [Grokzen/redis-py-cluster#461]
# Issue Type

[x] Bug (Typo)

# Steps to Replicate and Expected Behaviour

- Examine rediscluster/client.py, rediscluster/connection.py, tests/test_cluster_node_manager.py and observe `specefied`, however expect to see `specified`.
- Examine tests/test_commands.py and observe `impelmentation`, however expect to see `implementation`.
- Examine CONTRIBUTING.md, tests/test_commands.py and observe `uptream`, however expect to see `upstream`.
- Examine tests/test_cluster_node_manager.py and observe `itterate`, however expect to see `iterate`.
- Examine docs/logging.rst and observe `reccommended`, however expect to see `recommended`.
- Examine docs/pubsub.rst and observe `recieved`, however expect to see `received`.
- Examine tests/test_encoding_cluster.py and observe `preffered`, however expect to see `preferred`.
- Examine docs/pubsub.rst and observe `posiblity`, however expect to see `possibility`.
- Examine docs/upgrading.rst and observe `intervall`, however expect to see `interval`.
- Examine docs/index.rst and observe `exmaples`, however expect to see `examples`.
- Examine docs/development.rst and observe `documentaion`, however expect to see `documentation`.

# Notes

Semi-automated issue generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

To avoid wasting CI processing resources a branch with the fix has been
prepared but a pull request has not yet been created. A pull request fixing
the issue can be prepared from the link below, feel free to create it or
request @timgates42 create the PR. Alternatively if the fix is undesired please
close the issue with a small comment about the reasoning.

https://github.com/timgates42/redis-py-cluster/pull/new/bugfix_typos

Thanks.

**Comment by Grokzen** [comment]
@timgates42 CI resources are free from TravisCI so just post the PR already

**Comment by timgates42** [comment]
Thanks @Grokzen have done so
