### ISSUE TITLE
Where to fill in the password??

### ISSUE THREAD

**Issue by felix0080** [Grokzen/redis-py-cluster#466]
Where to fill in the password? Don't you have a password for Redis?

**Comment by holmboe** [comment]
@felix0080 Is this an issue (bug) or a discussion?

See https://github.com/Grokzen/redis-py-cluster/discussions

**Comment by felix0080** [comment]
> @felix0080 Is this an issue (bug) or a discussion?
> 
> See https://github.com/Grokzen/redis-py-cluster/discussions

https://github.com/Grokzen/redis-py-cluster/discussions/468
