### ISSUE TITLE
Implement thread based parallel pipeline execution

### ISSUE THREAD

**Issue by Grokzen** [Grokzen/redis-py-cluster#48]
We currently have a gevent implementation of a parallel pipeline runner, but it have some limitations. The biggest one is that it only works on python 2.x.

This issue should result in a PR that will implement a more general way to do paralell pipeline execution that follow these requirements.
- MUST work in 2.7 and 3.2-3.4, 3.1 is optional but is not required.
- Probably Thread based
- Should live in its own function
- Controll of what paralell runner to use should be specefied in this order
  - kwarg variable to RedisCluster() that should be used as default
  - kwarg variable to RedisCluster.pipeline() that if set should overwrite default the above
  - kwarg variable to StrictClusterPipeline()
  - Not sure if, but maybe as optional kwarg to StrictClusterPipeline.execute_... methods
- It should validate that the set pipeline method is available in the currnet running environment. That means it should fail with raised Exception if `gevent` is used on python 3.x for example.
- Extract `gevent` code into own function and use same interface as this new impl.

**Comment by jacobluo** [comment]
when i use gevent, pipeline occur exception: LoopExit('This operation would block forever',) 
how can i fix it ?

**Comment by Grokzen** [comment]
@jacobluo What version of the code are you running? And i guess you are running the pipeline with geevent, but just to give you a heads up, we removed the geevent code in favor for a better implementation for the next release. Do you have some better stack trace or info on how to debug this?

@72squared do you have any input or help you can provide?
