### ISSUE TITLE
Py-Redis-Cluster unable redirect read to replica(s)

### ISSUE THREAD

**Issue by pnthai88** [Grokzen/redis-py-cluster#487]
Hello everybody,

I'm making a cluster with single replica for each master.
For write, I will redirect it to master nodes; for read I redirect to replica nodes. For standalone redis, it's very simple. But in cluster, how do I perform it since all read and write always redirect to master nodes

```
cluster_replicaNodes = [a list slave's ips...]

def get_slaves():
    return RedisCluster(
        password="mypasswordisweak",
        startup_nodes=cluster_replicaNodes,
        readonly_mode=True,
        decode_responses=True,
    )
```

```
cluster_masterNodes = [a list master's ips...]

def get_master():
    return RedisCluster(
        password="mypasswordisweak",
        startup_nodes=cluster_masterNodes,
        decode_responses=True,
    )
```

The result of several hundred reads

![image](https://user-images.githubusercontent.com/8721600/137113685-9913b74b-ef80-45da-b000-3475aaf01ce5.png)

**Comment by Grokzen** [comment]
@pnthai88 I do not even get what you want to do with your initial code, reading from replica nodes is not how that feature works, you can't just send in a list of the slave nodes into the class constructor and expect it to only use those nodes. Even in that case the client class will query all the nodes you provided and still figure out all the master nodes and still do what the client is designed to do. If you want a working example of how reading from replicas work you should look at this example instead https://github.com/Grokzen/redis-py-cluster/blob/master/examples/pipeline-readonly-replicas.py as it shows how it really works. There is a mess in how there is essentially two options with read_from_replicas and readonly_mode and how to use them. But follow that example and it should start working for you.

The mentioned code change will not be implemented tho as that is not the solution to your problem, using read_from_replicas=True is.
