### ISSUE TITLE
Fix `redis._compat` import as redis-py 4.0 removes them

### ISSUE THREAD

**Issue by haobibo** [Grokzen/redis-py-cluster#489]
In `redis-py==4.0.0rc1`, `redis._compat` has been removed.
While the following code relies on it: https://github.com/Grokzen/redis-py-cluster/blob/master/rediscluster/connection.py#L22

**Comment by Grokzen** [comment]
@haobibo AWS is making a push to implement this lib into redis-py itself, but i see that it has been pushed back from the 4.0.0 release to 4.1.0 release so i might have to port the support for 4.0.0 into this lib, but i did not have plans to support 4.0.0 as they wore going to implement cluster support them self, I will have to think about that decision now as 4.1.0 will be even further out.

**Comment by thehananbhat** [comment]
The cluster client based on Grokzen's redis-py-cluster, has been added in redis-py Version 4.1.0-rc2 onwards, and now supersedes this library.
You can use the redis-py to connect to a cluster. Check this [Cluster Mode support for redis-py](https://github.com/redis/redis-py/releases/tag/v4.1.0rc2)

**Comment by haobibo** [comment]
THANKS!
