### ISSUE TITLE
archive repo since redis-py is cluster compatible 

### ISSUE THREAD

**Issue by raphaelauv** [Grokzen/redis-py-cluster#493]
If the repo https://github.com/redis/redis-py is now cluster compatible

https://github.com/redis/redis-py#cluster-mode
```
The cluster client is based on Grokzen's redis-py-cluster, has added bug fixes, and now supersedes that library. Support for these changes is thanks to his contributions.
```

This repo should be archive right ?

**Comment by Grokzen** [comment]
Has the PR been merged? i thought it was pushed back one major release. No this repo will not be put into archived mode, but yes for most general usage and purpose this repo will not be further developed if they have merged in the major support into the latest major version. This repo will probably serve more as a laboratory for redis and cluster moving forward then being the major client that is used for cluster support in the python eco system.
The longterm goal for this project was always to have this code base integrated into redis-py and finally it has happened :)

**Comment by raphaelauv** [comment]
You are right , the feature is only in a RC -> https://github.com/redis/redis-py/releases/tag/v4.1.0rc1

Maybe add a disclaimer in the readme of that repo when the 4.1.0 is in stable release.

**Comment by mquinnfd** [comment]
They've definitely published `4.1.0` now (11 days ago) https://github.com/redis/redis-py/releases

I currently use this repo (@Grokzen is a hero) but will be trialling switching over in the coming weeks, hopefully it's stable 👍

**Comment by chayim** [comment]
We worked with amazing @Grokzen to make this happen. He is such a hero!

**Comment by lu911** [comment]
@Grokzen is a hero. Thansk D:

**Comment by Grokzen** [comment]
Closing this issue as the README has been updated with an EOL notice. The project will not really be fully github archived yet
