### ISSUE TITLE
Support of Redis v4.1

### ISSUE THREAD

**Issue by okushnir-amplify** [Grokzen/redis-py-cluster#496]
Hi!
Are you planning to support redis v4.1+ anytime soon?
Thanks,
Oleksa

**Comment by Grokzen** [comment]
@okushnir-amplify Sorry had to lock the thread as you was opening and closing the issue.

The current plan that i will try to sort out in a little while is that this library will not support redis-py 4.1.0 or above. In 4.1.0 and above they have ported over the code from this library over to redis-py and they are done with it and it has launched so the development and support for newer redis-py versions will not be happening any more as the main development will be happening over there.

For now this lib will be the main library that you will use in any version prior to 4.1.0 of redis-py. This lib will not go away, but if you are using anything after 4.1.0 you should move over to redis-py only and stop using this library. Or if you must wait then you will have to remain on an older version of redis-py and the latest version of redis-py-cluster until you are ready to migrate over.

My longterm plans is to find some other use and move this repo over to be something else or maybe start up a new project where i can go back to exploring new ideas and things i want to develop around redis-py and try out different solutions and mechanism for redis-cluster and it's features.
