### ISSUE TITLE
how to use ACL in redis cluster client

### ISSUE THREAD

**Issue by smartnews-weitao** [Grokzen/redis-py-cluster#498]
Hello redis-py-cluster team. My redis cluster is enabled ACL, so i have a pair of username and password, however during the initialization of py-client, i didn't find any argument to let me define my username and password. And i didn't find any AUTH command that i can use after client is initialized. So any example will be appreciated. Thank you.

**Comment by Grokzen** [comment]
@smartnews-weitao All ACL commands is blocked when running in cluster mode within this client. What you need to do is to use `redis-py` and create a plain `Redis` instance to each of your nodes in your cluster and handle ACL:s for each server manually via your provisioning solution you are using. There are no plans to support ACL commands across the entire cluster at any point in the future.

I dont think we are compatible with the ACL authentications either and the only supported one is the old password solution. You will have to dig into redis-py source code for your release exactly how they support and work for authenticating. You should look into the Connection implementation becuase that is where authentication happens.
