### ISSUE TITLE
ImportError: cannot import name dictkeys on Python 2.7.3

### ISSUE THREAD

**Issue by stevewoolley** [Grokzen/redis-py-cluster#65]
using python 2.7.3
using redis-py-cluster 0.2.0

when trying to do a:
from rediscluster import RedisCluster

or

from rediscluster import StrictRedisCluster

receiving:

>>> from rediscluster import RedisCluster
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/rediscluster-0.5.3-py2.7.egg/rediscluster/__init__.py", line 12, in <module>
    from rediscluster.cluster_client import StrictRedisCluster
  File "/usr/local/lib/python2.7/dist-packages/rediscluster-0.5.3-py2.7.egg/rediscluster/cluster_client.py", line 5, in <module>
    from redis._compat import (
ImportError: cannot import name dictkeys

**Comment by stevewoolley** [comment]
Sorry for the red herring.....

this error occurred after installing reds-py-cluster via pip.

after installing from source, ran successfully.

Thanks

**Comment by Grokzen** [comment]
@stevewoolley Also i noticed that that stacktrace do not belong to my lib because the version is wrong. It states that you are using the package rediscluster with version `0.5.3` but sinc this lib is only in version `0.2.0` you must have installed the wrong package :]
