### ISSUE TITLE
Plan for cluster commands?

### ISSUE THREAD

**Issue by iandyh** [Grokzen/redis-py-cluster#71]
AFAIK, the commands in this page: http://redis.io/commands#cluster have not been implemented. Any plans to work on this?

If maintainers are currently busy, I may start to work on this in near future. :)

Thanks.

**Comment by Grokzen** [comment]
@iandyh If you would do this, do you have a plan for how to do it? Would you make a specialized class that just have these commands so that you do not accidentially use them in normal operation mode?

Also do you mean to just give the ability to use these commands and not reimplement the tool `redis-trib.rb` that can do alot more than just use these basic commands?

**Comment by iandyh** [comment]
@Grokzen For the first question, I haven't thought too much about the implementation yet. If it will be a specific class, naming it will be difficult: `RedisClusterCluster` looks weird to me. :) It might be look like `rc = RedisCluster(); rc.cluster.slots()`. 

For the second question, the reason why some cluster commands are needed is because I need to write a tool to manage the cluster. e.g. Add 10 new nodes to the cluster and move some slots to these new nodes. To achieve this, at least the `cluster slots` command is necessary to avoid parsing the raw results from `redis-trib.rb`. And the rest operations can be done via `redis-trib.rb` though. So the commands which retrieve information from cluster are on top priority.

**Comment by Grokzen** [comment]
About the name, i could go for something like `ClusterMgmt` or `RedisClusterMgmt` or something similar.

It should not be that big of a problem to implement this class from what i see in the docs at redis.io In most cases i can just make the function with a similar name and make them as simple as possible and let the caller handle as much logic as possible.

I will see if i can get some testable code up and running in a few days or so.

**Comment by iandyh** [comment]
@Grokzen https://github.com/Grokzen/redis-py-cluster/pull/73 I made a quick implementation so we can have something to discuss on.

**Comment by Grokzen** [comment]
@iandyh I will have a look at it later tonights

**Comment by Grokzen** [comment]
@iandyh Closing this based on the merged PR #73
