### ISSUE TITLE
ipython not found StrictRedisCluster

### ISSUE THREAD

**Issue by rfyiamcool** [Grokzen/redis-py-cluster#72]
I used pip install, that version could not import "StrictRedisCluster"

bug  git clone your redis-py-cluster;python setup.py install , fix the question。

Please update redis-py-cluster in pypi

**Comment by Grokzen** [comment]
@rfyiamcool Hi. Please see this issue and the awenser in there https://github.com/Grokzen/redis-py-cluster/issues/68 

In short you must look at the correct documentation at https://github.com/Grokzen/redis-py-cluster/tree/0.2.0

**Comment by rfyiamcool** [comment]
thanks You
