### ISSUE TITLE
StrictRedisCluster().info() not returning all nodes

### ISSUE THREAD

**Issue by Erve1879** [Grokzen/redis-py-cluster#79]
I'm using INFO to get usage stats for each of the nodes in my Redis Cluster, but it seems that ``.info()`` always fails to return details for a specific node (a slave node).

Using ``RedisClusterMgt().info()`` returns the details of all six nodes in the cluster and redis-cli reports the same data. Running INFO on the node which is always excluded from ``StrictRedisCluster().info()`` returns the expected stats: running as a slave in the correct cluster.

The missing node is not included in my ``startup_nodes`` (only the 3 masters).

I'm guessing this could be a bug in ``NodeManager``, but I'd appreciate a pointer or two before I dive into trying to debug the problem.... Thanks!

**Comment by mumumu** [comment]
> I'm using INFO to get usage stats for each of the nodes in my Redis Cluster, but it seems that .info() always fails to return details for a specific node (a slave node).
>
> The missing node is not included in my startup_nodes (only the 3 masters).

I can't reproduce above on redis-py-cluster 1.0.0 and the latest unstable branch.
What is your reproducible code?

```
$ redis-cli --version
redis-cli 3.0.2
$ redis-cli -p 7000 cluster nodes | sort -k 2
473c2eaabd94a1bdaae6b82569c29d6e6d0c3868 127.0.0.1:7000 myself,master - 0 0 1 connected 0-5460
9af5e607cb44c79671e4292ad95ef37e0878b8f7 127.0.0.1:7001 master - 0 1437251225775 2 connected 5461-10922
7b7b43609ce3ac1be56f05c2c45f2d2412407fa4 127.0.0.1:7002 master - 0 1437251225775 3 connected 10923-16383
931cb6d7e36b916853651883db595b3b8b6cb2bf 127.0.0.1:7003 slave 473c2eaabd94a1bdaae6b82569c29d6e6d0c3868 0 1437251224273 4 connected
552286c8c325884c4ada547a2ecb158b9d1ffd3d 127.0.0.1:7004 slave 9af5e607cb44c79671e4292ad95ef37e0878b8f7 0 1437251224773 5 connected
da2eb13079edceebd0ca4a2aba82053fd31aa3ae 127.0.0.1:7005 slave 7b7b43609ce3ac1be56f05c2c45f2d2412407fa4 0 1437251223771 6 connected
```

```
$ python
Python 2.7.9 (default, Mar  1 2015, 12:57:24) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from rediscluster import StrictRedisCluster
>>> startup_nodes = [{"host": "127.0.0.1", "port": "7000"}, {"host": "127.0.0.1", "port": "7001"}, {"host": "127.0.0.1", "port": "7002"}]
>>> rc = StrictRedisCluster(startup_nodes=startup_nodes, decode_responses=True)
>>> import json
>>> print json.dumps(sorted(rc.info().items(), key=lambda t: t[0]), indent=2)
[
  [
    "127.0.0.1:7000", 
    {
      "aof_rewrite_in_progress": 0, 
      ...
  ], 
  [
    "127.0.0.1:7001", 
    {
      "aof_rewrite_in_progress": 0, 
       ....
  ], 
  [
    "127.0.0.1:7002", 
    {
      "aof_rewrite_in_progress": 0, 
      ....
    }
  ], 
  [
    "127.0.0.1:7003", 
    {
      "aof_rewrite_in_progress": 0, 
      ....
    }
  ], 
  [
    "127.0.0.1:7004", 
    {
      "aof_rewrite_in_progress": 0, 
        ....
    }
  ], 
  [
    "127.0.0.1:7005", 
    {
      "aof_rewrite_in_progress": 0, 
      ....
    }
  ]
]
```

**Comment by Erve1879** [comment]
Thanks @mumumu - have been digging deeper and it seems that the slave node in question is not returning the correct response to ``CLUSTER SLOTS`` (it is not reporting itself as a slave, but ``CLUSTER INFO`` states that the slave is connected). Not sure what the issue is here, but it's clearly not with ``redis-py-cluster`` so I'll close this. Thanks for taking the time to check it out.
