### ISSUE TITLE
Tests break if the test cluster have been resharded

### ISSUE THREAD

**Issue by Grokzen** [Grokzen/redis-py-cluster#96]
When investigating the ASK errors and running all the resharding operations back and forth. It was discovered that some tests are very dependent on the redis cluster to be a certain way. By this i mean that each slot has to bee on the correct node because tests assume that when hashing a key it should be put in a certain slot that should be on a certain node.

A solution that might be worth to investigate is to create a mock client that can be configured so that the real cluster can be ignored and tests will allways pass no matter what the state of the cluster is in.

If you ever get broken tests of this kind. The simplest fix for now it to restart/reset your cluster and to reset all slots back to a initial 3 node configuration.

**Comment by 72squared** [comment]
I wonder if we could use flushall and cluster reset?

http://redis.io/commands/cluster-reset

Seems like the unit tests inside of redis cluster work this way.

https://github.com/antirez/redis/blob/846da5b22e7877614694b4bda94fe0fdca34ada9/tests/cluster/tests/includes/init-tests.tcl#L28

**Comment by Grokzen** [comment]
It is worth investigating atleast. It do not matter if tests run slow in travis-ci but it is not optimal if we add alot of time when running locally.

**Comment by Grokzen** [comment]
This could be dangerous to enable outside travis acctually, we do not want to modify a existing cluster that a developer is running, so it would have to be travis only but and there is already rather stable already. It could be that a test should be done against the cluster that is going to be used and determine if it is 3 nodes with 3 masters and 3 minions and if not then tests will simply fail because that is the assumed cluster setup.

**Comment by 72squared** [comment]
I have been using [redislite](https://github.com/yahoo/redislite) extensively in all my redis based tests recently because it reduces my dependencies in my test harness and allows me to predictably and reliably start up one or more redis instances on the fly. Wonder if we could make the tests use that? Then resetting the cluster wouldn't have to worry that you are modifying production data.

**Comment by Grokzen** [comment]
This issue is no longer relevant or active
