### ISSUE TITLE
refactor pipeline threads to experiment with parallel write/read pattern

### ISSUE THREAD

**Issue by 72squared** [Grokzen/redis-py-cluster#97]
We might not really need threads in pipelines if we first write to all the sockets for each node, sending the commands and wait to read the responses until all the writes have been sent first. This isn't perfect non-blocking i/o in the sense that you wouldn't be reading partial responses in parallel from the sockets, but in our case it may be good enough and in most cases might be even more performant than running a bunch of parallel threads, especially when the pipeline request maps to many many different nodes. Worth doing a prototype and building some performance benchmark comparisons.

**Comment by Grokzen** [comment]
Closing because of merged PR
