### ISSUE TITLE
refactor pipeline send_cluster_commands

### ISSUE THREAD

**Issue by 72squared** [Grokzen/redis-py-cluster#98]
This method is a huge unwieldy monster. If we get rid of threads it might shrink a bit but even still it'll be nasty. I'd like to take a stab at moving this logic into sub-tasks or possibly separate classes to ease understanding and breaking up the logic into more manageable chunks. However, I don't want to make any sacrifices on performance or break expectations on behavior so it'll need to be heavily tested.

**Comment by Grokzen** [comment]
Closing because of merged PR
